// Translation System for CleanLine Website
(function() {
    'use strict';

    // Translation dictionaries
    const translations = {
        en: {
            'nav.home': 'About us',
            'nav.services': 'Services',
            'nav.portfolio': 'Portfolio',
            'nav.pricing': 'Pricing',
            'hero.subtitle': ' ',
            'hero.title': 'Professional Cleaning Services in Bucharest — Home, Office & Deep Cleaning',
            'whychoose.subtitle': 'Why Choose Us',
            'whychoose.title': 'Why Choose Us?',
            'whychoose.description': 'We go beyond cleaning — we build trust through consistent quality and reliable service. Our team delivers clean, healthy, and comfortable spaces across Bucharest using modern methods and eco-friendly products.',
            'whychoose.feature1.title': 'Trained & Reliable Staff',
            'whychoose.feature1.desc': 'Professional and verified team members you can trust.',
            'whychoose.feature2.title': 'Flexible Scheduling',
            'whychoose.feature2.desc': 'We adapt to your schedule and specific needs.',
            'whychoose.feature3.title': 'Eco-Friendly Products',
            'whychoose.feature3.desc': 'Safe cleaning solutions for your family and pets.',
            'whychoose.feature4.title': 'Guaranteed Results',
            'whychoose.feature4.desc': 'Spotless results, every single time.',
            'whychoose.tagline': 'Simple, honest, and stress-free cleaning.',
            'trust.experience': 'Years of experience in Bucharest',
            'trust.completed': 'Hundreds of completed cleanings',
            'trust.pricing': 'Fixed pricing, no hidden costs',
            'trust.guarantee': 'Quality guarantee',
            'howitworks.subtitle': 'How It Works',
            'howitworks.title': 'How it works',
            'howitworks.description': 'Request → Quote → Cleaning → Guarantee',
            'howitworks.step1.title': 'Request',
            'howitworks.step1.desc': 'Contact us via WhatsApp, phone or email',
            'howitworks.step2.title': 'Quote',
            'howitworks.step2.desc': 'Get instant pricing based on your needs',
            'howitworks.step3.title': 'Cleaning',
            'howitworks.step3.desc': 'Our team arrives and completes the work',
            'howitworks.step4.title': 'Guarantee',
            'howitworks.step4.desc': 'Satisfaction guaranteed or we return',
            'featured.subtitle': 'Featured Service',
            'featured.title': 'Building Trust Through Spotless Results',
            'featured.description': 'We care about every space we clean. High-quality products and modern techniques ensure fresh, healthy results — every time.',
            'services.subtitle': ' ',
            'services.title': 'Why choose us',
            'service.office.title': 'Office Cleaning',
            'service.office.desc': 'Comprehensive office cleaning to keep your workplace fresh, sanitized and professional for employees and visitors.',
            'service.pool.title': 'Pool Cleaning',
            'service.pool.desc': 'Specialized pool cleaning and chemical balancing to ensure clear, safe water and well-maintained pool areas.',
            'service.carpet.title': 'Carpet Cleaning',
            'service.carpet.desc': 'Deep carpet and rug cleaning using professional equipment to remove dirt, stains, and allergens for a healthier home.',
            'service.kitchen.title': 'Kitchen Cleaning',
            'service.kitchen.desc': 'Thorough kitchen cleaning and degreasing to ensure food-preparation areas are spotless and hygienic.',
            'service.garden.title': 'Garden Cleaning',
            'service.garden.desc': 'Garden and outdoor area maintenance to keep lawns, paths and patios tidy and inviting year-round.',
            'service.window.title': 'Window Cleaning',
            'service.window.desc': 'Professional window and glass cleaning for streak-free, crystal-clear views — inside and out.',
            'services.light.title': 'Light Cleaning',
            'services.light.desc': 'Regular light cleaning to maintain freshness in your home',
            'lightcleaning.breadcrumb.home': 'Home',
            'lightcleaning.breadcrumb.current': 'Light Cleaning',
            'lightcleaning.pagetitle': 'Light Cleaning',
            'lightcleaning.features.title': 'What is included in light cleaning',
            'lightcleaning.features.subtitle': 'Our light cleaning includes basic procedures to maintain cleanliness and freshness in your home',
            'lightcleaning.feature1': 'Removing cobwebs and dust from visible areas and surfaces',
            'lightcleaning.feature2': 'Room disinfection',
            'lightcleaning.feature3': 'Washing furniture surfaces',
            'lightcleaning.feature4': 'Washing exterior and interior of appliances',
            'lightcleaning.feature5': 'Care for houseplants (by agreement)',
            'lightcleaning.feature6': 'Washing range hood',
            'lightcleaning.feature7': 'Washing refrigerator',
            'lightcleaning.feature8': 'Washing washing machine',
            'lightcleaning.feature9': 'Washing oven',
            'lightcleaning.feature10': 'Washing faucets and radiators',
            'lightcleaning.feature11': 'Washing walls in bathroom',
            'lightcleaning.pricing.title': 'Prices and Areas',
            'lightcleaning.table.select': 'Select',
            'lightcleaning.table.type': 'Property Type',
            'lightcleaning.table.area': 'Area',
            'lightcleaning.table.price': 'Price',
            'lightcleaning.table.time': 'Time',
            'lightcleaning.type.1room': '1 room apartment',
            'lightcleaning.type.2room': '2 room apartment',
            'lightcleaning.type.3room': '3 room apartment',
            'lightcleaning.type.4room': '4-5 room apartment',
            'lightcleaning.type.house': 'Houses, Villas',
            'lightcleaning.additional.title': 'Additional Services',
            'lightcleaning.additional.windows': 'Window washing (1 pc)',
            'lightcleaning.additional.cabinet': 'Washing inside of cabinet',
            'lightcleaning.additional.lamps': 'Washing lamps, floor lamps, chandeliers',
            'lightcleaning.additional.baseboards': 'Cleaning baseboards, cornices',
            'lightcleaning.additional.grout': 'Washing tile grout (1 m²)',
            'lightcleaning.additional.laundry': 'Washing personal items (5-6 kg)',
            'lightcleaning.additional.ironing': 'Ironing personal items (1 m²)',
            'lightcleaning.additional.bedding': 'Changing bed linen',
            'lightcleaning.additional.dishes': 'Washing dishes',
            'lightcleaning.additional.organizing': 'Sorting, organizing items',
            'lightcleaning.additional.zone': 'Any separate zone',
            'lightcleaning.additional.balcony': 'Complete cleaning of balcony, terrace, gazebo',
            'lightcleaning.additional.walls': 'Washing walls (5-10 Lei per m²)',
            'lightcleaning.calculator.title': '💰 Cost Calculator',
            'lightcleaning.calculator.placeholder': 'Select services to calculate cost...',
            'lightcleaning.calculator.total': 'Total:',
            'lightcleaning.calculator.clear': 'Clear all',
            'lightcleaning.area.upto120': 'up to 120 m²',
            'lightcleaning.area.upto500': 'up to 500 m²',
            'lightcleaning.time.hours': 'hours',
            'lightcleaning.service.windows': 'Window washing (1 pc)',
            'lightcleaning.service.cabinet': 'Washing inside of cabinet',
            'lightcleaning.service.lamps': 'Washing lamps, floor lamps, chandeliers',
            'lightcleaning.service.baseboards': 'Cleaning baseboards, cornices',
            'lightcleaning.service.grout': 'Washing tile grout (1 m²)',
            'lightcleaning.service.laundry': 'Washing personal items (5-6 kg)',
            'lightcleaning.service.ironing': 'Ironing personal items (1 m²)',
            'lightcleaning.service.bedding': 'Changing bed linen',
            'lightcleaning.service.dishes': 'Washing dishes',
            'lightcleaning.service.organizing': 'Sorting, organizing items',
            'lightcleaning.service.zone': 'Any separate zone',
            'lightcleaning.service.balcony': 'Complete cleaning of balcony, terrace, gazebo',
            'lightcleaning.service.walls': 'Washing walls (1 m²)',
            'readmore': 'Read more',
            'project.subtitle': 'Our Project',
            'project.title': 'We have done many latest cleaning project',
            'project.house': 'House Cleaning',
            'project.window': 'Window Cleaning',
            'project.pool': 'Pool Cleaning',
            'project.office': 'Office Cleaning',
            'project.carpet': 'Carpet Cleaning',
            'project.garden': 'Garden Cleaning',
            'beforeafter.subtitle': 'Our Results',
            'beforeafter.title': 'See the Difference',
            'beforeafter.description': 'Real transformations from our cleaning services',
            'beforeafter.before': 'Before',
            'beforeafter.after': 'After',
            'beforeafter.slide1.title': 'Living Room Deep Clean',
            'beforeafter.slide1.desc': 'Complete transformation with professional cleaning techniques',
            'beforeafter.slide2.title': 'Kitchen Refresh',
            'beforeafter.slide2.desc': 'Spotless surfaces and sanitized areas for a healthy home',
            'counter.subtitle': 'Happy Customer',
            'counter.title': 'Together we will explore new things',
            'counter.testimonies': 'Testimonies',
            'pricing.subtitle': 'Price & Plans',
            'pricing.title': 'Choose Your Perfect Plans',
            'pricing.residence': 'Residence Cleaning',
            'pricing.commercial': 'Commercial Cleaning',
            'pricing.construction': 'After Construction Cleaning',
            'pricing.construction.desc': 'Complete post-construction cleanup and detailed finishing',
            'pricing.construction.basic.title': 'Basic Post-Construction',
            'pricing.construction.basic.debris': 'Debris removal',
            'pricing.construction.basic.dust': 'Dust cleaning all surfaces',
            'pricing.construction.basic.floors': 'Floor cleaning & vacuuming',
            'pricing.construction.basic.windows': 'Window cleaning',
            'pricing.construction.standard.title': 'Standard Post-Construction',
            'pricing.construction.standard.all': 'All Basic services',
            'pricing.construction.standard.detailed': 'Detailed surface cleaning',
            'pricing.construction.standard.fixtures': 'Fixtures & fittings clean',
            'pricing.construction.standard.sanitize': 'Bathroom/kitchen sanitizing',
            'pricing.construction.premium.title': 'Premium Post-Construction',
            'pricing.construction.premium.all': 'All Standard services',
            'pricing.construction.premium.polish': 'Surface polishing',
            'pricing.construction.premium.stain': 'Paint/stain removal',
            'pricing.construction.premium.final': 'Final inspection & touch-ups',
            'pricing.construction.min': 'Min. order: 500 RON',
            'pricing.fixed': 'Fixed price – no hidden costs',
            'pricing.carpet.title': 'Carpets & Rugs Cleaning',
            'pricing.carpet.price': 'Price: 6 – 10 RON/m²',
            'pricing.carpet.minimum': '(minimum order 250 RON)',
            'pricing.room.title': 'Room-by-Room Services',
            'pricing.room.included': 'Included in general cleaning packages',
            'pricing.upholstery.title': 'Upholstery & Textiles Cleaning',
            'pricing.upholstery.desc': 'Professional cleaning without damaging materials',
            'contact.title': 'Contact Us',
            'contact.subtitle': 'Have questions or ready to book?',
            'contact.message': 'Send us a message and we\'ll get back to you as soon as possible!',
            'pricing.light.title': 'Light Maintenance',
            'pricing.light.dusting': 'Dusting visible surfaces',
            'pricing.light.bathroom': 'Bathroom maintenance',
            'pricing.light.kitchen': 'Kitchen surfaces',
            'pricing.light.vacuum': 'Vacuuming floors',
            'pricing.light.mopping': 'Mopping floors',
            'pricing.light.trash': 'Emptying trash bins',
            'pricing.light.min': 'Min. order: 250 RON',
            'pricing.standard.title': 'Standard Maintenance',
            'pricing.standard.all': 'All Light services',
            'pricing.standard.enhanced': 'Enhanced cleaning',
            'pricing.standard.appliances': 'Appliance exteriors',
            'pricing.standard.oven': 'Oven exterior',
            'pricing.standard.fridge': 'Refrigerator exterior',
            'pricing.standard.nodeep': 'No deep cleaning',
            'pricing.premium.title': 'Premium Maintenance',
            'pricing.premium.all': 'All Standard services',
            'pricing.premium.detailed': 'Detailed attention',
            'pricing.premium.extended': 'Extended surfaces',
            'pricing.premium.care': 'Premium care',
            'pricing.premium.nocabinets': 'No inside cabinets',
            'pricing.premium.noinside': 'No oven/fridge inside',
            'pricing.studio.title': 'Studio Apartment',
            'pricing.studio.complete': 'Complete cleaning',
            'pricing.studio.bathroom': 'Bathroom deep clean',
            'pricing.studio.kitchen': 'Kitchen deep clean',
            'pricing.studio.surfaces': 'All surfaces',
            'pricing.studio.vacuum': 'Vacuuming & mopping',
            'pricing.studio.fixed': 'Fixed price',
            'pricing.2room.title': '2-Room Apartment',
            'pricing.2room.living': 'Living room & bedroom',
            'pricing.3room.title': '3-Room Apartment',
            'pricing.3room.rooms': 'All rooms',
            'pricing.3room.extra': '2nd bathroom: +200 RON',
            'pricing.4room.title': '4-Room Apartment',
            'pricing.4room.rooms': 'All 4 rooms',
            'pricing.house.title': 'House / Villa',
            'pricing.house.bathrooms': 'All bathrooms',
            'pricing.house.custom': 'Custom quote available',
            'pricing.sofa.title': 'Sofa',
            'pricing.sofa.professional': 'Professional cleaning',
            'pricing.sofa.safe': 'Material-safe methods',
            'pricing.sofa.stain': 'Deep stain removal',
            'pricing.sofa.odor': 'Odor elimination',
            'pricing.sofa.other': 'Other models from 200 RON',
            'pricing.armchair.title': 'Armchair',
            'pricing.armchair.protection': 'Fabric protection',
            'pricing.mattress.title': 'Mattress',
            'pricing.mattress.deep': 'Deep cleaning',
            'pricing.mattress.mite': 'Dust mite removal',
            'pricing.mattress.allergen': 'Allergen elimination',
            'pricing.mattress.stain': 'Stain treatment',
            'pricing.mattress.sanitize': 'Sanitization',
            'pricing.chair.title': 'Upholstered Chair',
            'pricing.chair.quick': 'Quick drying',
            'pricing.chair.affordable': 'Affordable pricing',
            'pricing.carpet.small': 'Small Area',
            'pricing.carpet.deep': 'Deep carpet cleaning',
            'pricing.carpet.stain': 'Stain removal',
            'pricing.carpet.odor': 'Odor elimination',
            'pricing.carpet.fast': 'Fast drying',
            'pricing.carpet.eco': 'Eco-friendly products',
            'pricing.carpet.medium': 'Medium Area',
            'pricing.carpet.large': 'Large Area',
            'pricing.room.subtitle': 'Room-by-Room Services',
            'pricing.bathroom.title': '🛁 Bathroom',
            'pricing.bathroom.toilet': 'Toilet disinfection',
            'pricing.bathroom.tub': 'Bathtub/shower cleaning',
            'pricing.bathroom.limescale': 'Limescale removal',
            'pricing.bathroom.mirror': 'Mirror & glass cleaning',
            'pricing.bathroom.tiles': 'Tiles cleaning',
            'pricing.bathroom.floor': 'Floor disinfection',
            'pricing.bathroom.nocabinets': 'No inside cabinets',
            'pricing.kitchen.title': '🍽️ Kitchen',
            'pricing.kitchen.countertop': 'Countertop cleaning',
            'pricing.kitchen.tiles': 'Tiles/backsplash',
            'pricing.kitchen.cabinets': 'Cabinet fronts (exterior)',
            'pricing.kitchen.sink': 'Sink & tap anti-limescale',
            'pricing.kitchen.appliances': 'Appliances exterior',
            'pricing.kitchen.fridge': 'Inside fridge (extra)',
            'pricing.kitchen.oven': 'Inside oven (extra)',
            'pricing.living.title': '🛋️ Living Room',
            'pricing.living.dusting': 'Dusting all surfaces',
            'pricing.living.furniture': 'Furniture cleaning',
            'pricing.living.sofa': 'Sofa vacuuming',
            'pricing.living.doors': 'Doors & door frames',
            'pricing.living.baseboard': 'Baseboard wiping',
            'pricing.living.vacuum': 'Vacuuming floors',
            'pricing.living.mop': 'Mopping floors',
            'pricing.bedroom.title': '🛏️ Bedroom',
            'pricing.bedroom.dusting': 'Furniture dusting',
            'pricing.bedroom.nightstands': 'Nightstands & dressers',
            'pricing.bedroom.mirror': 'Mirror cleaning',
            'pricing.bedroom.vacuum': 'Vacuuming floors/carpet',
            'pricing.bedroom.mop': 'Mopping floors',
            'pricing.bedroom.doors': 'Doors & handles',
            'pricing.bedroom.nolinen': 'No bed linen change',
            'pricing.hallway.title': '🚪 Hallway',
            'pricing.hallway.dusting': 'Surface dusting',
            'pricing.hallway.doors': 'Doors & handles',
            'pricing.hallway.switches': 'Switches cleaning',
            'pricing.hallway.mirror': 'Mirror cleaning',
            'pricing.hallway.vacuum': 'Vacuuming floors',
            'pricing.hallway.mop': 'Mopping floors',
            'pricing.hallway.baseboard': 'Baseboard wiping',
            'button.getstarted': 'Get Started',
            'button.learnmore': 'Learn More',
            'contact.info': 'Contact Information',
            'contact.address': 'Address:',
            'contact.address.value': '203 Fake St. Mountain View, San Francisco, California, USA',
            'contact.phone': 'Phone:',
            'contact.email': 'Email:',
            'contact.whatsapp': 'WhatsApp:',
            'contact.hours': 'Opening Hours:',
            'contact.hours.response': 'Fast response',
            'contact.hours.time': '09:00–19:00',
            'contact.hours.sunday': 'Sunday closed',
            'contact.getin': 'Get In Touch',
            'freequote.button': 'Book Cleaning Now',
            'freequote.title': 'Get Your Free Quote',
            'freequote.contactus': 'Contact us today for a free quote!',
            'freequote.callnow': 'Call Now',
            'freequote.whatsapp': 'WhatsApp',
            'footer.description': 'CleanLine is a professional cleaning company specializing in Airbnb turnovers and general cleaning for houses and offices. We ensure spotless, well-prepared spaces with attention to detail, reliability, and high hygiene standards. Our goal is to help property owners and businesses maintain clean, welcoming environments effortlessly.',
            'footer.quicklinks': 'Quick Links',
            'footer.home': 'Home',
            'footer.about': 'About',
            'footer.services': 'Services',
            'footer.works': 'Works',
            'footer.blog': 'Blog',
            'footer.contact': 'Contact',
            'footer.questions': 'Have a Questions?',
            'testimony.title': 'Happy Customer',
            'menu.language': 'Menu',
            'home': 'About us',
            "services": "Services",
            "portfolio": "Portfolio",
            "pricing": "Pricing",
        },
        uk: {
            'nav.home': 'Про нас',
            'nav.services': 'Послуги',
            'nav.portfolio': 'Портфоліо',
            'nav.pricing': 'Ціни',
            'hero.subtitle': ' ',
            'hero.title': 'Професійні клінінгові послуги в Бухаресті — прибирання будинків, офісів та генеральне прибирання',
            'whychoose.subtitle': 'Чому обирають нас',
            'whychoose.title': 'Чому обирають нас?',
            'whychoose.description': 'Ми пропонуємо більше, ніж прибирання — ми будуємо довіру через якість та надійність. Працюємо в Бухаресті, створюючи чисті й безпечні простори з використанням сучасних та екологічних засобів.',
            'whychoose.feature1.title': 'Професійна команда',
            'whychoose.feature1.desc': 'Професійні та перевірені члени команди, яким можна довіряти.',
            'whychoose.feature2.title': 'Гнучкий графік',
            'whychoose.feature2.desc': 'Ми адаптуємось до вашого графіка та конкретних потреб.',
            'whychoose.feature3.title': 'Еко-засоби',
            'whychoose.feature3.desc': 'Безпечні засоби для прибирання для вашої родини та домашніх улюбленців.',
            'whychoose.feature4.title': 'Гарантований результат',
            'whychoose.feature4.desc': 'Бездоганні результати кожного разу.',
            'whychoose.tagline': 'Просто, надійно та без стресу.',
            'trust.experience': 'Досвід роботи в Бухаресті',
            'trust.completed': 'Сотні виконаних прибирань',
            'trust.pricing': 'Фіксована ціна',
            'trust.guarantee': 'Гарантія якості',
            'howitworks.subtitle': 'Як Ми Працюємо',
            'howitworks.title': 'Як ми працюємо',
            'howitworks.description': 'Запит → Розрахунок → Прибирання → Гарантія',
            'howitworks.step1.title': 'Запит',
            'howitworks.step1.desc': 'Зв\'яжіться з нами через WhatsApp, телефон або email',
            'howitworks.step2.title': 'Розрахунок',
            'howitworks.step2.desc': 'Отримайте миттєвий розрахунок вартості',
            'howitworks.step3.title': 'Прибирання',
            'howitworks.step3.desc': 'Наша команда приїжджає та виконує роботу',
            'howitworks.step4.title': 'Гарантія',
            'howitworks.step4.desc': 'Гарантія задоволення або ми повернемось',
            'featured.subtitle': 'Рекомендована послуга',
            'featured.title': 'Довіра через бездоганну чистоту',
            'featured.description': 'Ми дбаємо про кожен простір, застосовуючи якісні засоби та сучасні методи прибирання.',
            'services.subtitle': ' ',
            'services.title': 'Чому ми',
            'service.office.title': "Прибирання Офісу",
            'service.office.desc': 'Комплексне прибирання офісу для підтримки свіжості, санітарії та професійного вигляду для співробітників та відвідувачів.',
            'service.pool.title': 'Прибирання Басейну',
            'service.pool.desc': 'Спеціалізоване прибирання басейну та хімічне балансування для забезпечення чистої, безпечної води та доглянутих зон басейну.',
            'service.carpet.title': 'Прибирання Килимів',
            'service.carpet.desc': 'Глибоке чищення килимів та доріжок з використанням професійного обладнання для видалення бруду, плям та алергенів для здоровішого дому.',
            'service.kitchen.title': 'Прибирання Кухні',
            'service.kitchen.desc': 'Ретельне прибирання та знежирення кухні для забезпечення бездоганної чистоти та гігієни зон приготування їжі.',
            'service.garden.title': 'Прибирання Саду',
            'service.garden.desc': 'Обслуговування саду та відкритих територій для підтримки газонів, доріжок та патіо охайними та привабливими цілий рік.',
            'service.window.title': 'Миття Вікон',
            'service.window.desc': 'Професійне миття вікон та скла для бездоганного, кришталево чистого огляду — всередині та зовні.',
            'services.light.title': 'Легке Прибирання',
            'services.light.desc': 'Регулярне легке прибирання для підтримки свіжості вашого дому',
            'lightcleaning.breadcrumb.home': 'Головна',
            'lightcleaning.breadcrumb.current': 'Легке Прибирання',
            'lightcleaning.pagetitle': 'Легке Прибирання',
            'lightcleaning.features.title': 'Що входить в легке прибирання',
            'lightcleaning.features.subtitle': 'Наше легке прибирання включає основні процедури для підтримки чистоти та свіжості вашого дому',
            'lightcleaning.feature1': 'Видалення павутиння та пилу з видимих зон, поверхонь',
            'lightcleaning.feature2': 'Дезінфекція приміщення',
            'lightcleaning.feature3': 'Миття поверхні меблів',
            'lightcleaning.feature4': 'Миття зовнішньої та внутрішньої сторони побутової техніки',
            'lightcleaning.feature5': 'Догляд за домашніми рослинами (за узгодженням)',
            'lightcleaning.feature6': 'Миття витяжки',
            'lightcleaning.feature7': 'Миття холодильника',
            'lightcleaning.feature8': 'Миття пральної машини',
            'lightcleaning.feature9': 'Миття духової печі',
            'lightcleaning.feature10': 'Миття змішувачів та батарей',
            'lightcleaning.feature11': 'Миття стін в санвузлі',
            'lightcleaning.pricing.title': 'Ціни та площі',
            'lightcleaning.table.select': 'Обрати',
            'lightcleaning.table.type': 'Тип житла',
            'lightcleaning.table.area': 'Площа',
            'lightcleaning.table.price': 'Ціна',
            'lightcleaning.table.time': 'Час',
            'lightcleaning.type.1room': '1 кімнатна квартира',
            'lightcleaning.type.2room': '2 кімнатна квартира',
            'lightcleaning.type.3room': '3 кімнатна квартира',
            'lightcleaning.type.4room': '4-5 кімнатна квартира',
            'lightcleaning.type.house': 'Будинки, Вілли',
            'lightcleaning.additional.title': 'Додаткові послуги',
            'lightcleaning.additional.windows': 'Миття вікон (1 шт)',
            'lightcleaning.additional.cabinet': 'Миття внутрішньої частини шафи',
            'lightcleaning.additional.lamps': 'Миття ламп, торшерів, люстр',
            'lightcleaning.additional.baseboards': 'Чищення плінтусів, карнизів',
            'lightcleaning.additional.grout': 'Миття міжплиткових швів (1 м²)',
            'lightcleaning.additional.laundry': 'Прання особистих речей (5-6 кг)',
            'lightcleaning.additional.ironing': 'Прасування особистих речей (1 м²)',
            'lightcleaning.additional.bedding': 'Зміна постільної білизни',
            'lightcleaning.additional.dishes': 'Миття посуду',
            'lightcleaning.additional.organizing': 'Сортування, організація речей',
            'lightcleaning.additional.zone': 'Будь-яка окрема зона',
            'lightcleaning.additional.balcony': 'Повне прибирання балкону, тераси, альтанки',
            'lightcleaning.additional.walls': 'Миття стін (5-10 Lei за м²)',
            'lightcleaning.calculator.title': '💰 Калькулятор вартості',
            'lightcleaning.calculator.placeholder': 'Оберіть послуги для розрахунку вартості...',
            'lightcleaning.calculator.total': 'Підсумок:',
            'lightcleaning.calculator.clear': 'Очистити все',
            'lightcleaning.area.upto120': 'до 120 м²',
            'lightcleaning.area.upto500': 'до 500 м²',
            'lightcleaning.time.hours': 'год',
            'lightcleaning.service.windows': 'Миття вікон (1 шт)',
            'lightcleaning.service.cabinet': 'Миття внутрішньої частини шафи',
            'lightcleaning.service.lamps': 'Миття ламп, торшерів, люстр',
            'lightcleaning.service.baseboards': 'Чищення плінтусів, карнизів',
            'lightcleaning.service.grout': 'Миття міжплиткових швів (1 м²)',
            'lightcleaning.service.laundry': 'Прання особистих речей (5-6 кг)',
            'lightcleaning.service.ironing': 'Прасування особистих речей (1 м²)',
            'lightcleaning.service.bedding': 'Зміна постільної білизни',
            'lightcleaning.service.dishes': 'Миття посуду',
            'lightcleaning.service.organizing': 'Сортування, організація речей',
            'lightcleaning.service.zone': 'Будь-яка окрема зона',
            'lightcleaning.service.balcony': 'Повне прибирання балкону, тераси, альтанки',
            'lightcleaning.service.walls': 'Миття стін (1 м²)',
            'readmore': 'Читати далі',
            'project.subtitle': 'Наш Проект',
            'project.title': 'Ми виконали багато останніх проектів з прибирання',
            'project.house': 'Прибирання Будинку',
            'project.window': 'Миття Вікон',
            'project.pool': 'Прибирання Басейну',
            'project.office': 'Прибирання Офісу',
            'project.carpet': 'Прибирання Килимів',
            'project.garden': 'Прибирання Саду',
            'beforeafter.subtitle': 'Наші Результати',
            'beforeafter.title': 'Побачте Різницю',
            'beforeafter.description': 'Реальні трансформації від наших послуг прибирання',
            'beforeafter.before': 'До',
            'beforeafter.after': 'Після',
            'beforeafter.slide1.title': 'Глибоке прибирання вітальні',
            'beforeafter.slide1.desc': 'Повна трансформація з професійними техніками прибирання',
            'beforeafter.slide2.title': 'Оновлення кухні',
            'beforeafter.slide2.desc': 'Бездоганні поверхні та санітарні зони для здорового дому',
            'counter.subtitle': 'Задоволені Клієнти',
            'counter.title': 'Разом ми досліджуватимемо нові можливості',
            'counter.testimonies': 'Відгуки',
            'pricing.subtitle': 'Ціни та Плани',
            'pricing.title': 'Оберіть Ваш Ідеальний План',
            'pricing.residence': 'Прибирання Житлових Приміщень',
            'pricing.commercial': 'Комерційне Прибирання',
            'pricing.construction': 'Прибирання Після Будівництва',
            'pricing.construction.desc': 'Повне прибирання після будівництва та детальне доопрацювання',
            'pricing.construction.basic.title': 'Базове Після Будівництва',
            'pricing.construction.basic.debris': 'Видалення будівельного сміття',
            'pricing.construction.basic.dust': 'Очищення пилу з усіх поверхонь',
            'pricing.construction.basic.floors': 'Прибирання та пилососування підлоги',
            'pricing.construction.basic.windows': 'Миття вікон',
            'pricing.construction.standard.title': 'Стандартне Після Будівництва',
            'pricing.construction.standard.all': 'Всі базові послуги',
            'pricing.construction.standard.detailed': 'Детальне очищення поверхонь',
            'pricing.construction.standard.fixtures': 'Очищення сантехніки та фурнітури',
            'pricing.construction.standard.sanitize': 'Санітарна обробка ванної/кухні',
            'pricing.construction.premium.title': 'Преміум Після Будівництва',
            'pricing.construction.premium.all': 'Всі стандартні послуги',
            'pricing.construction.premium.polish': 'Полірування поверхонь',
            'pricing.construction.premium.stain': 'Видалення плям фарби',
            'pricing.construction.premium.final': 'Фінальна перевірка та доопрацювання',
            'pricing.construction.min': 'Мін. замовлення: 500 RON',
            'pricing.fixed': 'Фіксована ціна – без прихованих витрат',
            'pricing.carpet.title': 'Прибирання Килимів',
            'pricing.carpet.price': 'Ціна: 6 – 10 RON/м²',
            'pricing.carpet.minimum': '(мінімальне замовлення 250 RON)',
            'pricing.room.title': 'Послуги по Кімнатах',
            'pricing.room.included': 'Включено в пакети генерального прибирання',
            'pricing.upholstery.title': 'Прибирання М\'якої Меблів',
            'pricing.upholstery.desc': 'Професійне прибирання без пошкодження матеріалів',
            'contact.title': 'Зв\'яжіться з Нами',
            'contact.subtitle': 'Маєте питання або готові замовити?',
            'contact.message': 'Надішліть нам повідомлення, і ми зв\'яжемося з вами якнайшвидше!',
            'pricing.light.title': 'Легке Підтримання',
            'pricing.light.dusting': 'Витирання видимих поверхонь',
            'pricing.light.bathroom': 'Підтримання ванної кімнати',
            'pricing.light.kitchen': 'Кухонні поверхні',
            'pricing.light.vacuum': 'Пилососіння підлоги',
            'pricing.light.mopping': 'Миття підлоги',
            'pricing.light.trash': 'Виніс сміття',
            'pricing.light.min': 'Мін. замовлення: 250 RON',
            'pricing.standard.title': 'Стандартне Підтримання',
            'pricing.standard.all': 'Всі легкі послуги',
            'pricing.standard.enhanced': 'Покращене прибирання',
            'pricing.standard.appliances': 'Зовнішня сторона побутової техніки',
            'pricing.standard.oven': 'Зовнішня сторона духовки',
            'pricing.standard.fridge': 'Зовнішня сторона холодильника',
            'pricing.standard.nodeep': 'Без глибокого прибирання',
            'pricing.premium.title': 'Преміум Підтримання',
            'pricing.premium.all': 'Всі стандартні послуги',
            'pricing.premium.detailed': 'Детальна увага',
            'pricing.premium.extended': 'Розширені поверхні',
            'pricing.premium.care': 'Преміум догляд',
            'pricing.premium.nocabinets': 'Без внутрішньої частини шаф',
            'pricing.premium.noinside': 'Без внутрішньої частини духовки/холодильника',
            'pricing.studio.title': 'Квартира-Студія',
            'pricing.studio.complete': 'Повне прибирання',
            'pricing.studio.bathroom': 'Глибоке прибирання ванної',
            'pricing.studio.kitchen': 'Глибоке прибирання кухні',
            'pricing.studio.surfaces': 'Всі поверхні',
            'pricing.studio.vacuum': 'Пилососіння та миття',
            'pricing.studio.fixed': 'Фіксована ціна',
            'pricing.2room.title': '2-Кімнатна Квартира',
            'pricing.2room.living': 'Вітальня та спальня',
            'pricing.3room.title': '3-Кімнатна Квартира',
            'pricing.3room.rooms': 'Всі кімнати',
            'pricing.3room.extra': '2-га ванна: +200 RON',
            'pricing.4room.title': '4-Кімнатна Квартира',
            'pricing.4room.rooms': 'Всі 4 кімнати',
            'pricing.house.title': 'Будинок / Вілла',
            'pricing.house.bathrooms': 'Всі ванні кімнати',
            'pricing.house.custom': 'Доступна індивідуальна оцінка',
            'pricing.sofa.title': 'Диван',
            'pricing.sofa.professional': 'Професійне прибирання',
            'pricing.sofa.safe': 'Безпечні для матеріалу методи',
            'pricing.sofa.stain': 'Глибоке видалення плям',
            'pricing.sofa.odor': 'Усунення запахів',
            'pricing.sofa.other': 'Інші моделі від 200 RON',
            'pricing.armchair.title': 'Крісло',
            'pricing.armchair.protection': 'Захист тканини',
            'pricing.mattress.title': 'Матрац',
            'pricing.mattress.deep': 'Глибоке прибирання',
            'pricing.mattress.mite': 'Видалення пилових кліщів',
            'pricing.mattress.allergen': 'Усунення алергенів',
            'pricing.mattress.stain': 'Обробка плям',
            'pricing.mattress.sanitize': 'Санітарна обробка',
            'pricing.chair.title': 'М\'який Стілець',
            'pricing.chair.quick': 'Швидке висихання',
            'pricing.chair.affordable': 'Доступні ціни',
            'pricing.carpet.small': 'Мала Площа',
            'pricing.carpet.deep': 'Глибоке чищення килимів',
            'pricing.carpet.stain': 'Видалення плям',
            'pricing.carpet.odor': 'Усунення запахів',
            'pricing.carpet.fast': 'Швидке висихання',
            'pricing.carpet.eco': 'Екологічні засоби',
            'pricing.carpet.medium': 'Середня Площа',
            'pricing.carpet.large': 'Велика Площа',
            'pricing.room.subtitle': 'Послуги по Кімнатах',
            'pricing.bathroom.title': '🛁 Ванна Кімната',
            'pricing.bathroom.toilet': 'Дезінфекція туалету',
            'pricing.bathroom.tub': 'Прибирання ванни/душу',
            'pricing.bathroom.limescale': 'Видалення накипу',
            'pricing.bathroom.mirror': 'Миття дзеркала та скла',
            'pricing.bathroom.tiles': 'Прибирання плитки',
            'pricing.bathroom.floor': 'Дезінфекція підлоги',
            'pricing.bathroom.nocabinets': 'Без внутрішньої частини шаф',
            'pricing.kitchen.title': '🍽️ Кухня',
            'pricing.kitchen.countertop': 'Прибирання стільниці',
            'pricing.kitchen.tiles': 'Плитка/фартух',
            'pricing.kitchen.cabinets': 'Фасади шаф (зовні)',
            'pricing.kitchen.sink': 'Мийка та кран проти накипу',
            'pricing.kitchen.appliances': 'Побутова техніка зовні',
            'pricing.kitchen.fridge': 'Внутрішня частина холодильника (додатково)',
            'pricing.kitchen.oven': 'Внутрішня частина духовки (додатково)',
            'pricing.living.title': '🛋️ Вітальня',
            'pricing.living.dusting': 'Витирання всіх поверхонь',
            'pricing.living.furniture': 'Прибирання меблів',
            'pricing.living.sofa': 'Пилососіння дивану',
            'pricing.living.doors': 'Двері та дверні рами',
            'pricing.living.baseboard': 'Витирання плінтусів',
            'pricing.living.vacuum': 'Пилососіння підлоги',
            'pricing.living.mop': 'Миття підлоги',
            'pricing.bedroom.title': '🛏️ Спальня',
            'pricing.bedroom.dusting': 'Витирання меблів',
            'pricing.bedroom.nightstands': 'Тумбочки та комоди',
            'pricing.bedroom.mirror': 'Миття дзеркала',
            'pricing.bedroom.vacuum': 'Пилососіння підлоги/килима',
            'pricing.bedroom.mop': 'Миття підлоги',
            'pricing.bedroom.doors': 'Двері та ручки',
            'pricing.bedroom.nolinen': 'Без зміни постільної білизни',
            'pricing.hallway.title': '🚪 Передпокій',
            'pricing.hallway.dusting': 'Витирання поверхонь',
            'pricing.hallway.doors': 'Двері та ручки',
            'pricing.hallway.switches': 'Прибирання вимикачів',
            'pricing.hallway.mirror': 'Миття дзеркала',
            'pricing.hallway.vacuum': 'Пилососіння підлоги',
            'pricing.hallway.mop': 'Миття підлоги',
            'pricing.hallway.baseboard': 'Витирання плінтусів',
            'button.getstarted': 'Розпочати',
            'button.learnmore': 'Дізнатися Більше',
            'contact.info': 'Контактна Інформація',
            'contact.address': 'Адреса:',
            'contact.address.value': 'Бухарест зона Dristor',
            'contact.phone': 'Телефон:',
            'contact.email': 'Email:',
            'contact.whatsapp': 'WhatsApp:',
            'contact.hours': 'Години роботи:',
            'contact.hours.response': 'Швидка відповідь',
            'contact.hours.time': '09:00–19:00',
            'contact.hours.sunday': 'Неділя — вихідний',
            'contact.getin': 'Зв\'яжіться',
            'freequote.button': 'Замовити прибирання',
            'freequote.title': 'Отримайте Безкоштовну Пропозицію',
            'freequote.contactus': 'Зв\'яжіться з нами сьогодні для безкоштовної пропозиції!',
            'freequote.callnow': 'Зателефонуйте Зараз',
            'freequote.whatsapp': 'WhatsApp',
            'footer.description': 'CleanLine — професійна клінінгова компанія, що спеціалізується на підготовці Airbnb та генеральному прибиранні будинків та офісів. Ми забезпечуємо бездоганно чисті, добре підготовлені приміщення з увагою до деталей, надійністю та високими стандартами гігієни. Наша мета — допомогти власникам нерухомості та бізнесу легко підтримувати чисте, привітне середовище.',
            'footer.quicklinks': 'Швидкі Посилання',
            'footer.home': 'Головна',
            'footer.about': 'Про нас',
            'footer.services': 'Послуги',
            'footer.works': 'Роботи',
            'footer.blog': 'Блог',
            'footer.contact': 'Контакт',
            'footer.questions': 'Маєте Питання?',
            'testimony.title': 'Задоволені Клієнти',
            'menu.language': 'Меню',
            'home': 'Про нас',
            "services": "Послуги",
            "portfolio": "Портфоліо",
            "pricing": "Ціни",
        },
        ru: {
            'nav.home': 'О нас',
            'nav.services': 'Услуги',
            'nav.portfolio': 'Портфолио',
            'nav.pricing': 'Цены',
            'hero.subtitle': ' ',
            'hero.title': 'Профессиональные клининговые услуги в Бухаресте — уборка домов, офисов и генеральная уборка',
            'whychoose.subtitle': 'Почему выбирают нас',
            'whychoose.title': 'Почему выбирают нас?',
            'whychoose.description': 'Мы не просто убираем — мы создаём доверие благодаря стабильному качеству и ответственному подходу. Работаем в Бухаресте, обеспечивая чистые и безопасные пространства с помощью современных и экологичных средств.',
            'whychoose.feature1.title': 'Профессиональный и проверенный персонал',
            'whychoose.feature1.desc': 'Профессиональная и проверенная команда, которой можно доверять.',
            'whychoose.feature2.title': 'Удобный график',
            'whychoose.feature2.desc': 'Мы адаптируемся к вашему графику и конкретным потребностям.',
            'whychoose.feature3.title': 'Экологичные средства',
            'whychoose.feature3.desc': 'Безопасные чистящие средства для вашей семьи и домашних животных.',
            'whychoose.feature4.title': 'Гарантия результата',
            'whychoose.feature4.desc': 'Безупречные результаты каждый раз.',
            'whychoose.tagline': 'Чисто, честно и без лишних забот.',
            'trust.experience': 'Опыт работы в Бухаресте',
            'trust.completed': 'Сотни выполненных уборок',
            'trust.pricing': 'Фиксированная цена',
            'trust.guarantee': 'Гарантия качества',
            'howitworks.subtitle': 'Как Мы Работаем',
            'howitworks.title': 'Как мы работаем',
            'howitworks.description': 'Заявка → Расчёт → Уборка → Гарантия',
            'howitworks.step1.title': 'Заявка',
            'howitworks.step1.desc': 'Свяжитесь с нами через WhatsApp, телефон или email',
            'howitworks.step2.title': 'Расчёт',
            'howitworks.step2.desc': 'Получите мгновенный расчёт стоимости',
            'howitworks.step3.title': 'Уборка',
            'howitworks.step3.desc': 'Наша команда приезжает и выполняет работу',
            'howitworks.step4.title': 'Гарантия',
            'howitworks.step4.desc': 'Гарантия удовлетворения или мы вернёмся',
            'stats.subtitle': 'Наша Статистика',
            'stats.title': 'Качество, Которое Можно Измерить',
            'stats.description': 'Смотрите наше стремление к совершенству в цифрах',
            'stats.satisfaction.title': 'Удовлетворённость Клиентов',
            'stats.satisfaction.desc': 'На основе отзывов клиентов',
            'stats.repeat.title': 'Повторные Клиенты',
            'stats.repeat.desc': 'Клиенты, которые возвращаются за услугами',
            'stats.ontime.title': 'Прибытие Вовремя',
            'stats.ontime.desc': 'Пунктуальное предоставление услуг',
            'stats.quality.title': 'Стандарты Качества',
            'stats.quality.desc': 'Соблюдение высоких стандартов качества',
            'services.types.title': 'Выберите Тип Услуги',
            'services.types.subtitle': 'Выберите тип уборки, чтобы узнать больше',
            'services.types.residential': 'Жилые помещения',
            'services.types.commercial': 'Коммерческие',
            'services.types.deep': 'Генеральная уборка',
            'services.types.special': 'Специализированные',
            'services.types.residential.title': 'Услуги Уборки Жилых Помещений',
            'services.types.residential.desc': 'Профессиональная уборка дома, адаптированная к вашим потребностям. От регулярного обслуживания до генеральной уборки — мы поддерживаем ваше жилое пространство в безупречном состоянии.',
            'services.types.residential.item1': 'Регулярная уборка дома',
            'services.types.residential.item2': 'Уборка квартиры',
            'services.types.residential.item3': 'Уборка при переезде',
            'services.types.residential.item4': 'Глубокая уборка кухни и ванной',
            'services.types.commercial.title': 'Услуги Коммерческой Уборки',
            'services.types.commercial.desc': 'Поддерживайте ваше деловое пространство чистым и профессиональным. Мы эффективно обслуживаем офисы, торговые помещения и коммерческую недвижимость.',
            'services.types.commercial.item1': 'Уборка офисов',
            'services.types.commercial.item2': 'Обслуживание торговых помещений',
            'services.types.commercial.item3': 'Услуги в нерабочее время',
            'services.types.commercial.item4': 'Гибкий график',
            'services.types.deep.title': 'Услуги Генеральной Уборки',
            'services.types.deep.desc': 'Комплексная генеральная уборка для тщательного обновления. Идеально для весенней уборки, после ремонта или особых случаев.',
            'services.types.deep.item1': 'Полная генеральная уборка дома',
            'services.types.deep.item2': 'Уборка после строительства',
            'services.types.deep.item3': 'Чистка внутренних частей техники',
            'services.types.deep.item4': 'Детальная обработка поверхностей',
            'services.types.special.title': 'Специализированные Услуги Уборки',
            'services.types.special.desc': 'Экспертная уборка для конкретных потребностей. Ковры, обивка, окна и многое другое под контролем обученных профессионалов.',
            'services.types.special.item1': 'Чистка ковров и обивки',
            'services.types.special.item2': 'Мытьё окон',
            'services.types.special.item3': 'Обслуживание бассейнов',
            'services.types.special.item4': 'Уборка сада',
            'button.booknow': 'Заказать',
            'featured.subtitle': 'Рекомендуемая услуга',
            'featured.title': 'Доверие через безупречную чистоту',
            'featured.description': 'Мы заботимся о каждом объекте, используя качественные средства и современные технологии для идеального результата.',
            'services.subtitle': ' ',
            'services.title': 'Почему мы',
            'service.office.title': 'Уборка Офиса',
            'service.office.desc': 'Комплексная уборка офиса для поддержания свежести, санитарии и профессионального вида для сотрудников и посетителей.',
            'service.pool.title': 'Уборка Бассейна',
            'service.pool.desc': 'Специализированная уборка бассейна и химический баланс для обеспечения чистой, безопасной воды и ухоженных зон бассейна.',
            'service.carpet.title': 'Уборка Ковров',
            'service.carpet.desc': 'Глубокая чистка ковров и ковриков с использованием профессионального оборудования для удаления грязи, пятен и аллергенов для более здорового дома.',
            'service.kitchen.title': 'Уборка Кухни',
            'service.kitchen.desc': 'Тщательная уборка и обезжиривание кухни для обеспечения безупречной чистоты и гигиены зон приготовления пищи.',
            'service.garden.title': 'Уборка Сада',
            'service.garden.desc': 'Обслуживание сада и открытых территорий для поддержания газонов, дорожек и патио опрятными и привлекательными круглый год.',
            'service.window.title': 'Мытье Окон',
            'service.window.desc': 'Профессиональное мытье окон и стекла для безупречного, кристально чистого обзора — внутри и снаружи.',
            'services.light.title': 'Легкая Уборка',
            'services.light.desc': 'Регулярная легкая уборка для поддержания свежести вашего дома',
            'lightcleaning.breadcrumb.home': 'Главная',
            'lightcleaning.breadcrumb.current': 'Легкая Уборка',
            'lightcleaning.pagetitle': 'Легкая Уборка',
            'lightcleaning.features.title': 'Что входит в легкую уборку',
            'lightcleaning.features.subtitle': 'Наша легкая уборка включает в себя основные процедуры для поддержания чистоты и свежести вашего дома',
            'lightcleaning.feature1': 'Удаление паутины и пыли с видимых зон, поверхностей',
            'lightcleaning.feature2': 'Дезинфекция помещения',
            'lightcleaning.feature3': 'Мытье поверхности мебели',
            'lightcleaning.feature4': 'Мытье внешней и внутренней стороны бытовой техники',
            'lightcleaning.feature5': 'Уход за домашними растениями (по согласованию)',
            'lightcleaning.feature6': 'Мойка вытяжки',
            'lightcleaning.feature7': 'Мойка холодильника',
            'lightcleaning.feature8': 'Мойка стиральной машины',
            'lightcleaning.feature9': 'Мойка духовой печи',
            'lightcleaning.feature10': 'Мойка смесителей и батарей',
            'lightcleaning.feature11': 'Мойка стен в санузле',
            'lightcleaning.pricing.title': 'Цены и площади',
            'lightcleaning.table.select': 'Выбрать',
            'lightcleaning.table.type': 'Тип жилья',
            'lightcleaning.table.area': 'Площадь',
            'lightcleaning.table.price': 'Цена',
            'lightcleaning.table.time': 'Время',
            'lightcleaning.type.1room': '1 комнатная квартира',
            'lightcleaning.type.2room': '2 комнатная квартира',
            'lightcleaning.type.3room': '3 комнатная квартира',
            'lightcleaning.type.4room': '4-5 комнатная квартира',
            'lightcleaning.type.house': 'Дома, Виллы',
            'lightcleaning.additional.title': 'Дополнительные услуги',
            'lightcleaning.additional.windows': 'Мойка окон (1 шт)',
            'lightcleaning.additional.cabinet': 'Мойка внутренней части шкафа',
            'lightcleaning.additional.lamps': 'Мойка ламп, торшеров, люстр',
            'lightcleaning.additional.baseboards': 'Чистка плинтусов, карнизов',
            'lightcleaning.additional.grout': 'Мойка межплиточных швов (1 м²)',
            'lightcleaning.additional.laundry': 'Стирка личных вещей (5-6 кг)',
            'lightcleaning.additional.ironing': 'Глажка личных вещей (1 м²)',
            'lightcleaning.additional.bedding': 'Смена постельного белья',
            'lightcleaning.additional.dishes': 'Мойка посуды',
            'lightcleaning.additional.organizing': 'Сортировка, организация вещей',
            'lightcleaning.additional.zone': 'Любая отдельная зона',
            'lightcleaning.additional.balcony': 'Полная уборка балкона, террасы, беседки',
            'lightcleaning.additional.walls': 'Мойка стен (5-10 Lei за м²)',
            'lightcleaning.calculator.title': '💰 Калькулятор стоимости',
            'lightcleaning.calculator.placeholder': 'Выберите услуги для расчета стоимости...',
            'lightcleaning.calculator.total': 'Итого:',
            'lightcleaning.calculator.clear': 'Очистить все',
            'lightcleaning.area.upto120': 'до 120 м²',
            'lightcleaning.area.upto500': 'до 500 м²',
            'lightcleaning.time.hours': 'час',
            'lightcleaning.service.windows': 'Мойка окон (1 шт)',
            'lightcleaning.service.cabinet': 'Мойка внутренней части шкафа',
            'lightcleaning.service.lamps': 'Мойка ламп, торшеров, люстр',
            'lightcleaning.service.baseboards': 'Чистка плинтусов, карнизов',
            'lightcleaning.service.grout': 'Мойка межплиточных швов (1 м²)',
            'lightcleaning.service.laundry': 'Стирка личных вещей (5-6 кг)',
            'lightcleaning.service.ironing': 'Глажка личных вещей (1 м²)',
            'lightcleaning.service.bedding': 'Смена постельного белья',
            'lightcleaning.service.dishes': 'Мойка посуды',
            'lightcleaning.service.organizing': 'Сортировка, организация вещей',
            'lightcleaning.service.zone': 'Любая отдельная зона',
            'lightcleaning.service.balcony': 'Полная уборка балкона, террасы, беседки',
            'lightcleaning.service.walls': 'Мойка стен (1 м²)',
            'readmore': 'Читать далее',
            'project.subtitle': 'Наш Проект',
            'project.title': 'Мы выполнили много последних проектов по уборке',
            'project.house': 'Уборка Дома',
            'project.window': 'Мытье Окон',
            'project.pool': 'Уборка Бассейна',
            'project.office': 'Уборка Офиса',
            'project.carpet': 'Уборка Ковров',
            'project.garden': 'Уборка Сада',
            'beforeafter.subtitle': 'Наши Результаты',
            'beforeafter.title': 'Увидьте Разницу',
            'beforeafter.description': 'Реальные трансформации от наших услуг уборки',
            'beforeafter.before': 'До',
            'beforeafter.after': 'После',
            'beforeafter.slide1.title': 'Глубокая уборка гостиной',
            'beforeafter.slide1.desc': 'Полная трансформация с профессиональными техниками уборки',
            'beforeafter.slide2.title': 'Обновление кухни',
            'beforeafter.slide2.desc': 'Безупречные поверхности и санитарные зоны для здорового дома',
            'counter.subtitle': 'Довольные Клиенты',
            'counter.title': 'Вместе мы исследуем новые возможности',
            'counter.testimonies': 'Отзывы',
            'pricing.subtitle': 'Цены и Планы',
            'pricing.title': 'Выберите Ваш Идеальный План',
            'pricing.residence': 'Уборка Жилых Помещений',
            'pricing.commercial': 'Коммерческая Уборка',
            'pricing.construction': 'Уборка После Строительства',
            'pricing.construction.desc': 'Полная уборка после строительства и детальная доработка',
            'pricing.construction.basic.title': 'Базовая После Строительства',
            'pricing.construction.basic.debris': 'Удаление строительного мусора',
            'pricing.construction.basic.dust': 'Очистка пыли со всех поверхностей',
            'pricing.construction.basic.floors': 'Уборка и пылесосание пола',
            'pricing.construction.basic.windows': 'Мытьё окон',
            'pricing.construction.standard.title': 'Стандартная После Строительства',
            'pricing.construction.standard.all': 'Все базовые услуги',
            'pricing.construction.standard.detailed': 'Детальная очистка поверхностей',
            'pricing.construction.standard.fixtures': 'Очистка сантехники и фурнитуры',
            'pricing.construction.standard.sanitize': 'Санитарная обработка ванной/кухни',
            'pricing.construction.premium.title': 'Премиум После Строительства',
            'pricing.construction.premium.all': 'Все стандартные услуги',
            'pricing.construction.premium.polish': 'Полировка поверхностей',
            'pricing.construction.premium.stain': 'Удаление пятен краски',
            'pricing.construction.premium.final': 'Финальная проверка и доработка',
            'pricing.construction.min': 'Мин. заказ: 500 RON',
            'pricing.fixed': 'Фиксированная цена – без скрытых расходов',
            'pricing.carpet.title': 'Уборка Ковров',
            'pricing.carpet.price': 'Цена: 6 – 10 RON/м²',
            'pricing.carpet.minimum': '(минимальный заказ 250 RON)',
            'pricing.room.title': 'Услуги по Комнатам',
            'pricing.room.included': 'Включено в пакеты генеральной уборки',
            'pricing.upholstery.title': 'Уборка Мягкой Мебели',
            'pricing.upholstery.desc': 'Профессиональная уборка без повреждения материалов',
            'contact.title': 'Свяжитесь с Нами',
            'contact.subtitle': 'Есть вопросы или готовы заказать?',
            'contact.message': 'Отправьте нам сообщение, и мы свяжемся с вами как можно скорее!',
            'pricing.light.title': 'Легкое Поддержание',
            'pricing.light.dusting': 'Протирание видимых поверхностей',
            'pricing.light.bathroom': 'Поддержание ванной комнаты',
            'pricing.light.kitchen': 'Кухонные поверхности',
            'pricing.light.vacuum': 'Пылесошение пола',
            'pricing.light.mopping': 'Мытье пола',
            'pricing.light.trash': 'Вынос мусора',
            'pricing.light.min': 'Мин. заказ: 250 RON',
            'pricing.standard.title': 'Стандартное Поддержание',
            'pricing.standard.all': 'Все легкие услуги',
            'pricing.standard.enhanced': 'Улучшенная уборка',
            'pricing.standard.appliances': 'Внешняя сторона бытовой техники',
            'pricing.standard.oven': 'Внешняя сторона духовки',
            'pricing.standard.fridge': 'Внешняя сторона холодильника',
            'pricing.standard.nodeep': 'Без глубокой уборки',
            'pricing.premium.title': 'Премиум Поддержание',
            'pricing.premium.all': 'Все стандартные услуги',
            'pricing.premium.detailed': 'Детальное внимание',
            'pricing.premium.extended': 'Расширенные поверхности',
            'pricing.premium.care': 'Премиум уход',
            'pricing.premium.nocabinets': 'Без внутренней части шкафов',
            'pricing.premium.noinside': 'Без внутренней части духовки/холодильника',
            'pricing.studio.title': 'Квартира-Студия',
            'pricing.studio.complete': 'Полная уборка',
            'pricing.studio.bathroom': 'Глубокая уборка ванной',
            'pricing.studio.kitchen': 'Глубокая уборка кухни',
            'pricing.studio.surfaces': 'Все поверхности',
            'pricing.studio.vacuum': 'Пылесошение и мытье',
            'pricing.studio.fixed': 'Фиксированная цена',
            'pricing.2room.title': '2-Комнатная Квартира',
            'pricing.2room.living': 'Гостиная и спальня',
            'pricing.3room.title': '3-Комнатная Квартира',
            'pricing.3room.rooms': 'Все комнаты',
            'pricing.3room.extra': '2-я ванная: +200 RON',
            'pricing.4room.title': '4-Комнатная Квартира',
            'pricing.4room.rooms': 'Все 4 комнаты',
            'pricing.house.title': 'Дом / Вилла',
            'pricing.house.bathrooms': 'Все ванные комнаты',
            'pricing.house.custom': 'Доступна индивидуальная оценка',
            'pricing.sofa.title': 'Диван',
            'pricing.sofa.professional': 'Профессиональная уборка',
            'pricing.sofa.safe': 'Безопасные для материала методы',
            'pricing.sofa.stain': 'Глубокое удаление пятен',
            'pricing.sofa.odor': 'Устранение запахов',
            'pricing.sofa.other': 'Другие модели от 200 RON',
            'pricing.armchair.title': 'Кресло',
            'pricing.armchair.protection': 'Защита ткани',
            'pricing.mattress.title': 'Матрас',
            'pricing.mattress.deep': 'Глубокая уборка',
            'pricing.mattress.mite': 'Удаление пылевых клещей',
            'pricing.mattress.allergen': 'Устранение аллергенов',
            'pricing.mattress.stain': 'Обработка пятен',
            'pricing.mattress.sanitize': 'Санитарная обработка',
            'pricing.chair.title': 'Мягкий Стул',
            'pricing.chair.quick': 'Быстрое высыхание',
            'pricing.chair.affordable': 'Доступные цены',
            'pricing.carpet.small': 'Малая Площадь',
            'pricing.carpet.deep': 'Глубокая чистка ковров',
            'pricing.carpet.stain': 'Удаление пятен',
            'pricing.carpet.odor': 'Устранение запахов',
            'pricing.carpet.fast': 'Быстрое высыхание',
            'pricing.carpet.eco': 'Экологичные средства',
            'pricing.carpet.medium': 'Средняя Площадь',
            'pricing.carpet.large': 'Большая Площадь',
            'pricing.room.subtitle': 'Услуги по Комнатам',
            'pricing.bathroom.title': '🛁 Ванная Комната',
            'pricing.bathroom.toilet': 'Дезинфекция туалета',
            'pricing.bathroom.tub': 'Уборка ванны/душа',
            'pricing.bathroom.limescale': 'Удаление накипи',
            'pricing.bathroom.mirror': 'Мытье зеркала и стекла',
            'pricing.bathroom.tiles': 'Уборка плитки',
            'pricing.bathroom.floor': 'Дезинфекция пола',
            'pricing.bathroom.nocabinets': 'Без внутренней части шкафов',
            'pricing.kitchen.title': '🍽️ Кухня',
            'pricing.kitchen.countertop': 'Уборка столешницы',
            'pricing.kitchen.tiles': 'Плитка/фартук',
            'pricing.kitchen.cabinets': 'Фасады шкафов (снаружи)',
            'pricing.kitchen.sink': 'Мойка и кран против накипи',
            'pricing.kitchen.appliances': 'Бытовая техника снаружи',
            'pricing.kitchen.fridge': 'Внутренняя часть холодильника (дополнительно)',
            'pricing.kitchen.oven': 'Внутренняя часть духовки (дополнительно)',
            'pricing.living.title': '🛋️ Гостиная',
            'pricing.living.dusting': 'Протирание всех поверхностей',
            'pricing.living.furniture': 'Уборка мебели',
            'pricing.living.sofa': 'Пылесошение дивана',
            'pricing.living.doors': 'Двери и дверные рамы',
            'pricing.living.baseboard': 'Протирание плинтусов',
            'pricing.living.vacuum': 'Пылесошение пола',
            'pricing.living.mop': 'Мытье пола',
            'pricing.bedroom.title': '🛏️ Спальня',
            'pricing.bedroom.dusting': 'Протирание мебели',
            'pricing.bedroom.nightstands': 'Тумбочки и комоды',
            'pricing.bedroom.mirror': 'Мытье зеркала',
            'pricing.bedroom.vacuum': 'Пылесошение пола/ковра',
            'pricing.bedroom.mop': 'Мытье пола',
            'pricing.bedroom.doors': 'Двери и ручки',
            'pricing.bedroom.nolinen': 'Без смены постельного белья',
            'pricing.hallway.title': '🚪 Прихожая',
            'pricing.hallway.dusting': 'Протирание поверхностей',
            'pricing.hallway.doors': 'Двери и ручки',
            'pricing.hallway.switches': 'Уборка выключателей',
            'pricing.hallway.mirror': 'Мытье зеркала',
            'pricing.hallway.vacuum': 'Пылесошение пола',
            'pricing.hallway.mop': 'Мытье пола',
            'pricing.hallway.baseboard': 'Протирание плинтусов',
            'button.getstarted': 'Начать',
            'button.learnmore': 'Узнать Больше',
            'contact.info': 'Контактная Информация',
            'contact.address': 'Адрес:',
            'contact.address.value': 'Бухарест зона Dristor',
            'contact.phone': 'Телефон:',
            'contact.email': 'Email:',
            'contact.whatsapp': 'WhatsApp:',
            'contact.hours': 'Часы работы:',
            'contact.hours.response': 'Быстрый ответ',
            'contact.hours.time': '09:00–19:00',
            'contact.hours.sunday': 'Воскресенье — выходной',
            'contact.getin': 'Свяжитесь',
            'freequote.button': 'Заказать уборку',
            'freequote.title': 'Получите Бесплатное Предложение',
            'freequote.contactus': 'Свяжитесь с нами сегодня для бесплатного предложения!',
            'freequote.callnow': 'Позвонить Сейчас',
            'freequote.whatsapp': 'WhatsApp',
            'footer.description': 'CleanLine — профессиональная клининговая компания, специализирующаяся на подготовке Airbnb и генеральной уборке домов и офисов. Мы обеспечиваем безупречно чистые, хорошо подготовленные помещения с вниманием к деталям, надежностью и высокими стандартами гигиены. Наша цель — помочь владельцам недвижимости и бизнеса легко поддерживать чистую, приветливую среду.',
            'footer.quicklinks': 'Быстрые Ссылки',
            'footer.home': 'Главная',
            'footer.about': 'О нас',
            'footer.services': 'Услуги',
            'footer.works': 'Работы',
            'footer.blog': 'Блог',
            'footer.contact': 'Контакт',
            'footer.questions': 'Есть Вопросы?',
            'testimony.title': 'Довольные Клиенты',
            'menu.language': 'Меню',
            'home': 'О нас',
            "services": "Услуги",
            "portfolio": "Портфолио",
            "pricing": "Цены",
        },
        ro: {
            'nav.home': 'Despre noi',
            'nav.services': 'Servicii',
            'nav.portfolio': 'Portofoliu',
            'nav.pricing': 'Prețuri',
            'hero.subtitle': ' ',
            'hero.title': 'Servicii Profesionale de Curățenie în București — Curățenie pentru Locuințe, Birouri și Curățenie Generală',
            'whychoose.subtitle': 'De ce să ne alegi',
            'whychoose.title': 'De ce să ne alegi?',
            'whychoose.description': 'Oferim mai mult decât curățenie — construim încredere prin servicii constante și rezultate impecabile. Echipa noastră creează spații curate, sănătoase și confortabile în București, folosind metode moderne și produse eco.',
            'whychoose.feature1.title': 'Personal profesionist și verificat',
            'whychoose.feature1.desc': 'Personal profesionist și verificat în care poți avea încredere.',
            'whychoose.feature2.title': 'Program flexibil, adaptat nevoilor tale',
            'whychoose.feature2.desc': 'Ne adaptăm programului și nevoilor tale specifice.',
            'whychoose.feature3.title': 'Produse ecologice, sigure pentru familie',
            'whychoose.feature3.desc': 'Soluții de curățenie sigure pentru familia și animalele tale.',
            'whychoose.feature4.title': 'Rezultate garantate, de fiecare dată',
            'whychoose.feature4.desc': 'Rezultate impecabile, de fiecare dată.',
            'whychoose.tagline': 'Curățenie simplă, corectă și fără stres.',
            'trust.experience': '3 ani de experiență în București',
            'trust.completed': 'Sute de curățenii realizate',
            'trust.pricing': 'Preț fix, fără costuri ascunse',
            'trust.guarantee': 'Garanția calității serviciilor',
            'howitworks.subtitle': 'Cum Lucrăm',
            'howitworks.title': 'Cum funcționează?',
            'howitworks.description': 'Cerere → Ofertă → Curățenie → Garanție',
            'howitworks.step1.title': 'Cerere',
            'howitworks.step1.desc': 'Contactați-ne prin WhatsApp, telefon sau email',
            'howitworks.step2.title': 'Ofertă',
            'howitworks.step2.desc': 'Primiți prețul instant în funcție de nevoile dvs.',
            'howitworks.step3.title': 'Curățenie',
            'howitworks.step3.desc': 'Echipa noastră sosește și finalizează munca',
            'howitworks.step4.title': 'Garanție',
            'howitworks.step4.desc': 'Satisfacție garantată sau revenim',
            'featured.subtitle': 'Serviciu de Top',
            'featured.title': 'Construim încredere prin rezultate impecabile',
            'featured.description': 'Ne pasă de fiecare spațiu. Folosim produse de calitate și tehnici moderne pentru un mediu curat, proaspăt și sănătos — de fiecare dată.',
            'services.subtitle': ' ',
            'services.title': 'De ce ne alegeți',
            'service.office.title': 'Curățenie Birou',
            'service.office.desc': 'Curățenie completă de birou pentru a menține locul de muncă proaspăt, igienizat și profesional pentru angajați și vizitatori.',
            'service.pool.title': 'Curățenie Piscină',
            'service.pool.desc': 'Curățenie specializată de piscină și echilibrare chimică pentru a asigura apă clară, sigură și zone de piscină bine întreținute.',
            'service.carpet.title': 'Curățenie Covoare',
            'service.carpet.desc': 'Curățenie profundă a covoarelor și preșurilor folosind echipamente profesionale pentru a elimina murdăria, petele și alergenii pentru o casă mai sănătoasă.',
            'service.kitchen.title': 'Curățenie Bucătărie',
            'service.kitchen.desc': 'Curățenie amănunțită a bucătăriei și degresare pentru a asigura că zonele de preparare a alimentelor sunt impecabile și igienice.',
            'service.garden.title': 'Curățenie Grădină',
            'service.garden.desc': 'Întreținere grădină și zone exterioare pentru a menține gazonul, aleile și terasele curate și primitoare pe tot parcursul anului.',
            'service.window.title': 'Curățenie Ferestre',
            'service.window.desc': 'Curățenie profesională a ferestrelor și geamurilor pentru vederi cristaline, fără urme — interior și exterior.',
            'services.light.title': 'Curățenie Ușoară',
            'services.light.desc': 'Curățenie ușoară regulată pentru menținerea prospeții casei',
            'lightcleaning.breadcrumb.home': 'Acasă',
            'lightcleaning.breadcrumb.current': 'Curățenie Ușoară',
            'lightcleaning.pagetitle': 'Curățenie Ușoară',
            'lightcleaning.features.title': 'Ce este inclus în curățenia ușoară',
            'lightcleaning.features.subtitle': 'Curățenia noastră ușoară include proceduri de bază pentru menținerea curățeniei și prospeții casei dumneavoastră',
            'lightcleaning.feature1': 'Îndepărtarea pânzelor de păianjen și a prafului din zonele vizibile și suprafețele',
            'lightcleaning.feature2': 'Dezinfectarea încăperii',
            'lightcleaning.feature3': 'Spălarea suprafețelor mobilierului',
            'lightcleaning.feature4': 'Spălarea exteriorului și interiorului aparatelor de uz casnic',
            'lightcleaning.feature5': 'Îngrijirea plantelor de interior (prin acord)',
            'lightcleaning.feature6': 'Spălarea hotei',
            'lightcleaning.feature7': 'Spălarea frigiderului',
            'lightcleaning.feature8': 'Spălarea mașinii de spălat',
            'lightcleaning.feature9': 'Spălarea cuptorului',
            'lightcleaning.feature10': 'Spălarea robinetelor și radiatoarelor',
            'lightcleaning.feature11': 'Spălarea pereților în baie',
            'lightcleaning.pricing.title': 'Prețuri și suprafețe',
            'lightcleaning.table.select': 'Selectează',
            'lightcleaning.table.type': 'Tip proprietate',
            'lightcleaning.table.area': 'Suprafață',
            'lightcleaning.table.price': 'Preț',
            'lightcleaning.table.time': 'Timp',
            'lightcleaning.type.1room': 'Apartament 1 cameră',
            'lightcleaning.type.2room': 'Apartament 2 camere',
            'lightcleaning.type.3room': 'Apartament 3 camere',
            'lightcleaning.type.4room': 'Apartament 4-5 camere',
            'lightcleaning.type.house': 'Case, Vile',
            'lightcleaning.additional.title': 'Servicii suplimentare',
            'lightcleaning.additional.windows': 'Spălat ferestre (1 buc)',
            'lightcleaning.additional.cabinet': 'Spălat interiorul dulapului',
            'lightcleaning.additional.lamps': 'Spălat lămpi, veioze, candelabre',
            'lightcleaning.additional.baseboards': 'Curățat plinte, cornișe',
            'lightcleaning.additional.grout': 'Spălat rosturile faianței (1 m²)',
            'lightcleaning.additional.laundry': 'Spălat articole personale (5-6 kg)',
            'lightcleaning.additional.ironing': 'Călcat articole personale (1 m²)',
            'lightcleaning.additional.bedding': 'Schimbat lenjeriei de pat',
            'lightcleaning.additional.dishes': 'Spălat vasele',
            'lightcleaning.additional.organizing': 'Sortare, organizare articole',
            'lightcleaning.additional.zone': 'Orice zonă separată',
            'lightcleaning.additional.balcony': 'Curățenie completă balcon, terasă, foișor',
            'lightcleaning.additional.walls': 'Spălat pereți (5-10 Lei pe m²)',
            'lightcleaning.calculator.title': '💰 Calculator costuri',
            'lightcleaning.calculator.placeholder': 'Selectați serviciile pentru a calcula costul...',
            'lightcleaning.calculator.total': 'Total:',
            'lightcleaning.calculator.clear': 'Șterge tot',
            'lightcleaning.area.upto120': 'până la 120 m²',
            'lightcleaning.area.upto500': 'până la 500 m²',
            'lightcleaning.time.hours': 'ore',
            'lightcleaning.service.windows': 'Spălat ferestre (1 buc)',
            'lightcleaning.service.cabinet': 'Spălat interiorul dulapului',
            'lightcleaning.service.lamps': 'Spălat lămpi, veioze, candelabre',
            'lightcleaning.service.baseboards': 'Curățat plinte, cornișe',
            'lightcleaning.service.grout': 'Spălat rosturile faianței (1 m²)',
            'lightcleaning.service.laundry': 'Spălat articole personale (5-6 kg)',
            'lightcleaning.service.ironing': 'Călcat articole personale (1 m²)',
            'lightcleaning.service.bedding': 'Schimbat lenjeriei de pat',
            'lightcleaning.service.dishes': 'Spălat vasele',
            'lightcleaning.service.organizing': 'Sortare, organizare articole',
            'lightcleaning.service.zone': 'Orice zonă separată',
            'lightcleaning.service.balcony': 'Curățenie completă balcon, terasă, foișor',
            'lightcleaning.service.walls': 'Spălat pereți (1 m²)',
            'readmore': 'Citește mai mult',
            'counter.testimonies': 'Mărturii',
            'project.subtitle': 'Proiectul Nostru',
            'project.title': 'Am realizat multe proiecte de curățenie recente',
            'project.house': 'Curățenie Casă',
            'project.window': 'Curățenie Ferestre',
            'project.pool': 'Curățenie Piscină',
            'project.office': 'Curățenie Birou',
            'project.carpet': 'Curățenie Covoare',
            'project.garden': 'Curățenie Grădină',
            'beforeafter.subtitle': 'Rezultatele Noastre',
            'beforeafter.title': 'Vezi Diferența',
            'beforeafter.description': 'Transformări reale din serviciile noastre de curățenie',
            'beforeafter.before': 'Înainte',
            'beforeafter.after': 'După',
            'beforeafter.slide1.title': 'Curățenie Profundă Salon',
            'beforeafter.slide1.desc': 'Transformare completă cu tehnici profesionale de curățenie',
            'beforeafter.slide2.title': 'Reîmprospătare Bucătărie',
            'beforeafter.slide2.desc': 'Suprafețe impecabile și zone sanitarizate pentru o casă sănătoasă',
            'counter.subtitle': 'Clienți Mulțumiți',
            'counter.title': 'Împreună vom explora lucruri noi',
            'pricing.subtitle': 'Prețuri & Planuri',
            'pricing.title': 'Alege Planurile Tale Perfecte',
            'pricing.residence': 'Curățenie Rezidențială',
            'pricing.commercial': 'Curățenie Comercială',
            'pricing.construction': 'Curățenie După Construcție',
            'pricing.construction.desc': 'Curățenie completă post-construcție și finisaje detaliate',
            'pricing.construction.basic.title': 'De Bază După Construcție',
            'pricing.construction.basic.debris': 'Îndepărtare resturi construcție',
            'pricing.construction.basic.dust': 'Curățare praf toate suprafețele',
            'pricing.construction.basic.floors': 'Curățare & aspirare pardoseli',
            'pricing.construction.basic.windows': 'Curățare ferestre',
            'pricing.construction.standard.title': 'Standard După Construcție',
            'pricing.construction.standard.all': 'Toate serviciile de bază',
            'pricing.construction.standard.detailed': 'Curățare detaliată suprafețe',
            'pricing.construction.standard.fixtures': 'Curățare sanitare & feronerie',
            'pricing.construction.standard.sanitize': 'Igienizare baie/bucătărie',
            'pricing.construction.premium.title': 'Premium După Construcție',
            'pricing.construction.premium.all': 'Toate serviciile standard',
            'pricing.construction.premium.polish': 'Lustruire suprafețe',
            'pricing.construction.premium.stain': 'Îndepărtare pete vopsea',
            'pricing.construction.premium.final': 'Inspecție finală & retușuri',
            'pricing.construction.min': 'Comandă min: 500 RON',
            'pricing.fixed': 'Preț fix – fără costuri ascunse',
            'pricing.carpet.title': 'Curățenie Covoare & Preșuri',
            'pricing.carpet.price': 'Preț: 6 – 10 RON/m²',
            'pricing.carpet.minimum': '(comandă minimă 250 RON)',
            'pricing.room.title': 'Servicii Cameră cu Cameră',
            'pricing.room.included': 'Incluse în pachetele de curățenie generală',
            'pricing.upholstery.title': 'Curățenie Tapițerie & Textile',
            'pricing.upholstery.desc': 'Curățenie profesională fără deteriorarea materialelor',
            'contact.title': 'Contactează-ne',
            'contact.subtitle': 'Ai întrebări sau ești gata să rezervi?',
            'contact.message': 'Trimite-ne un mesaj și te vom contacta cât mai curând posibil!',
            'pricing.light.title': 'Întreținere Ușoară',
            'pricing.light.dusting': 'Ștergere praf suprafețe vizibile',
            'pricing.light.bathroom': 'Întreținere baie',
            'pricing.light.kitchen': 'Suprafețe bucătărie',
            'pricing.light.vacuum': 'Aspirare pardoseli',
            'pricing.light.mopping': 'Spălare pardoseli',
            'pricing.light.trash': 'Golire coșuri de gunoi',
            'pricing.light.min': 'Comandă minimă: 250 RON',
            'pricing.standard.title': 'Întreținere Standard',
            'pricing.standard.all': 'Toate serviciile Ușoare',
            'pricing.standard.enhanced': 'Curățenie îmbunătățită',
            'pricing.standard.appliances': 'Exterioare aparate',
            'pricing.standard.oven': 'Exterior cuptor',
            'pricing.standard.fridge': 'Exterior frigider',
            'pricing.standard.nodeep': 'Fără curățenie profundă',
            'pricing.premium.title': 'Întreținere Premium',
            'pricing.premium.all': 'Toate serviciile Standard',
            'pricing.premium.detailed': 'Atenție detaliată',
            'pricing.premium.extended': 'Suprafețe extinse',
            'pricing.premium.care': 'Îngrijire premium',
            'pricing.premium.nocabinets': 'Fără interior dulapuri',
            'pricing.premium.noinside': 'Fără interior cuptor/frigider',
            'pricing.studio.title': 'Apartament Garsonieră',
            'pricing.studio.complete': 'Curățenie completă',
            'pricing.studio.bathroom': 'Curățenie profundă baie',
            'pricing.studio.kitchen': 'Curățenie profundă bucătărie',
            'pricing.studio.surfaces': 'Toate suprafețele',
            'pricing.studio.vacuum': 'Aspirare & spălare',
            'pricing.studio.fixed': 'Preț fix',
            'pricing.2room.title': 'Apartament 2 Camere',
            'pricing.2room.living': 'Salon & dormitor',
            'pricing.3room.title': 'Apartament 3 Camere',
            'pricing.3room.rooms': 'Toate camerele',
            'pricing.3room.extra': 'A 2-a baie: +200 RON',
            'pricing.4room.title': 'Apartament 4 Camere',
            'pricing.4room.rooms': 'Toate cele 4 camere',
            'pricing.house.title': 'Casă / Vilă',
            'pricing.house.bathrooms': 'Toate băile',
            'pricing.house.custom': 'Ofertă personalizată disponibilă',
            'pricing.sofa.title': 'Canapea',
            'pricing.sofa.professional': 'Curățenie profesională',
            'pricing.sofa.safe': 'Metode sigure pentru materiale',
            'pricing.sofa.stain': 'Îndepărtare profundă pete',
            'pricing.sofa.odor': 'Eliminare mirosuri',
            'pricing.sofa.other': 'Alte modele de la 200 RON',
            'pricing.armchair.title': 'Fotoliu',
            'pricing.armchair.protection': 'Protecție țesătură',
            'pricing.mattress.title': 'Saltea',
            'pricing.mattress.deep': 'Curățenie profundă',
            'pricing.mattress.mite': 'Îndepărtare acarieni',
            'pricing.mattress.allergen': 'Eliminare alergeni',
            'pricing.mattress.stain': 'Tratament pete',
            'pricing.mattress.sanitize': 'Igienizare',
            'pricing.chair.title': 'Scaun Tapițat',
            'pricing.chair.quick': 'Uscare rapidă',
            'pricing.chair.affordable': 'Preț accesibil',
            'pricing.carpet.small': 'Suprafață Mică',
            'pricing.carpet.deep': 'Curățenie profundă covoare',
            'pricing.carpet.stain': 'Îndepărtare pete',
            'pricing.carpet.odor': 'Eliminare mirosuri',
            'pricing.carpet.fast': 'Uscare rapidă',
            'pricing.carpet.eco': 'Produse ecologice',
            'pricing.carpet.medium': 'Suprafață Medie',
            'pricing.carpet.large': 'Suprafață Mare',
            'pricing.room.subtitle': 'Servicii Cameră cu Cameră',
            'pricing.bathroom.title': '🛁 Baie',
            'pricing.bathroom.toilet': 'Dezinfectare toaletă',
            'pricing.bathroom.tub': 'Curățare cadă/duș',
            'pricing.bathroom.limescale': 'Îndepărtare calcar',
            'pricing.bathroom.mirror': 'Curățare oglindă & sticlă',
            'pricing.bathroom.tiles': 'Curățare faianță',
            'pricing.bathroom.floor': 'Dezinfectare pardoseală',
            'pricing.bathroom.nocabinets': 'Fără interior dulapuri',
            'pricing.kitchen.title': '🍽️ Bucătărie',
            'pricing.kitchen.countertop': 'Curățare blat',
            'pricing.kitchen.tiles': 'Faianță/lambriuri',
            'pricing.kitchen.cabinets': 'Fețe dulapuri (exterior)',
            'pricing.kitchen.sink': 'Chiuvetă & robinet anti-calcar',
            'pricing.kitchen.appliances': 'Exterior aparate',
            'pricing.kitchen.fridge': 'Interior frigider (suplimentar)',
            'pricing.kitchen.oven': 'Interior cuptor (suplimentar)',
            'pricing.living.title': '🛋️ Salon',
            'pricing.living.dusting': 'Ștergere praf toate suprafețele',
            'pricing.living.furniture': 'Curățare mobilier',
            'pricing.living.sofa': 'Aspirare canapea',
            'pricing.living.doors': 'Uși & tocuri',
            'pricing.living.baseboard': 'Ștergere plinte',
            'pricing.living.vacuum': 'Aspirare pardoseli',
            'pricing.living.mop': 'Spălare pardoseli',
            'pricing.bedroom.title': '🛏️ Dormitor',
            'pricing.bedroom.dusting': 'Ștergere praf mobilier',
            'pricing.bedroom.nightstands': 'Noptiere & comode',
            'pricing.bedroom.mirror': 'Curățare oglindă',
            'pricing.bedroom.vacuum': 'Aspirare pardoseli/covor',
            'pricing.bedroom.mop': 'Spălare pardoseli',
            'pricing.bedroom.doors': 'Uși & mânere',
            'pricing.bedroom.nolinen': 'Fără schimbat lenjerie pat',
            'pricing.hallway.title': '🚪 Hol',
            'pricing.hallway.dusting': 'Ștergere praf suprafețe',
            'pricing.hallway.doors': 'Uși & mânere',
            'pricing.hallway.switches': 'Curățare întrerupătoare',
            'pricing.hallway.mirror': 'Curățare oglindă',
            'pricing.hallway.vacuum': 'Aspirare pardoseli',
            'pricing.hallway.mop': 'Spălare pardoseli',
            'pricing.hallway.baseboard': 'Ștergere plinte',
            'button.getstarted': 'Începe Acum',
            'button.learnmore': 'Află Mai Mult',
            'contact.info': 'Informații de Contact',
            'contact.address': 'Adresă:',
            'contact.address.value': '203 Fake St. Mountain View, San Francisco, California, USA',
            'contact.phone': 'Telefon:',
            'contact.email': 'Email:',
            'contact.whatsapp': 'WhatsApp:',
            'contact.hours': 'Program:',
            'contact.hours.response': 'Răspuns rapid',
            'contact.hours.time': '09:00–19:00',
            'contact.hours.sunday': 'Duminică închis',
            'contact.getin': 'Contactează-ne',
            'freequote.button': 'Programează curățenia',
            'freequote.title': 'Obțineți Oferta Dumneavoastră Gratuită',
            'freequote.contactus': 'Contactați-ne astăzi pentru o ofertă gratuită!',
            'freequote.callnow': 'Apelați Acum',
            'freequote.whatsapp': 'WhatsApp',
            'footer.description': 'CleanLine este o companie profesională de curățenie specializată în pregătirea proprietăților Airbnb și curățenie generală pentru case și birouri. Asigurăm spații impecabile, bine pregătite cu atenție la detalii, fiabilitate și standarde înalte de igienă. Scopul nostru este să ajutăm proprietarii și afacerile să mențină medii curate și primitoare fără efort.',
            'footer.quicklinks': 'Link-uri Rapide',
            'footer.home': 'Acasă',
            'footer.about': 'Despre',
            'footer.services': 'Servicii',
            'footer.works': 'Lucrări',
            'footer.blog': 'Blog',
            'footer.contact': 'Contact',
            'footer.questions': 'Ai Întrebări?',
            'testimony.title': 'Clienți Mulțumiți',
            'menu.language': 'Meniu',
            'home': 'Despre noi',
            "services": "Servicii",
            "portfolio": "Portofoliu",
            "pricing": "Prețuri",

        }
    };

    // Current language
    let currentLang = localStorage.getItem('language') || 'ro';

    // Initialize translation on page load
    function init() {
        // Set initial language
        updateLanguage(currentLang, false);

        // Add click event to language dropdown options
        const languageOptions = document.querySelectorAll('.lang-option');
        languageOptions.forEach(function(option) {
            option.addEventListener('click', function(e) {
                e.preventDefault();
                const selectedLang = this.getAttribute('data-lang');
                updateLanguage(selectedLang, true);

                // Close the dropdown after selection
                const dropdown = document.querySelector('.dropdown-menu');
                if (dropdown && dropdown.classList.contains('show')) {
                    dropdown.classList.remove('show');
                }
            });
        });
    }

    // Toggle between languages
    function toggleLanguage() {
        // This function is no longer used with dropdown
        // Keep for backwards compatibility
        const langs = ['en', 'uk', 'ru', 'ro'];
        const currentIndex = langs.indexOf(currentLang);
        const nextIndex = (currentIndex + 1) % langs.length;
        currentLang = langs[nextIndex];
        updateLanguage(currentLang, true);
    }

    // Update all translatable elements
    function updateLanguage(lang, saveToStorage) {
        currentLang = lang;

        // Save preference to localStorage
        if (saveToStorage) {
            localStorage.setItem('language', lang);
        }

        // Update language indicator
        const currentLangElement = document.getElementById('currentLang');
        if (currentLangElement) {
            const langNames = {
                'en': 'EN',
                'uk': 'UA',
                'ru': 'RU',
                'ro': 'RO'
            };
            currentLangElement.textContent = langNames[lang] || lang.toUpperCase();
        }

        // Update HTML lang attribute
        document.documentElement.lang = lang;

        // Translate all elements with data-translate attribute
        const elements = document.querySelectorAll('[data-translate]');
        elements.forEach(function(element) {
            const key = element.getAttribute('data-translate');
            if (translations[lang] && translations[lang][key]) {
                element.textContent = translations[lang][key];
            }
        });

        // Add smooth transition effect
        elements.forEach(function(element) {
            element.style.transition = 'opacity 0.3s ease';
            element.style.opacity = '0';
            setTimeout(function() {
                element.style.opacity = '1';
            }, 50);
        });

        // Dispatch custom event for language change
        const languageChangeEvent = new CustomEvent('languageChanged', {
            detail: { language: lang }
        });
        window.dispatchEvent(languageChangeEvent);
    }

    // Wait for DOM to be ready
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

    // Export getTranslation function for use in other scripts
    window.getTranslation = function(key) {
        const lang = currentLang || 'ro';
        if (translations[lang] && translations[lang][key]) {
            return translations[lang][key];
        }
        return key; // Return key if translation not found
    };

    // Export getCurrentLanguage function
    window.getCurrentLanguage = function() {
        return currentLang || 'ro';
    };

})();
