// Translation System for CleanLine Website
(function() {
    'use strict';

    // Translation dictionaries
    const translations = {
        en: {
            'nav.home': 'Home',
            'nav.services': 'Services',
            'nav.portfolio': 'Portfolio',
            'nav.pricing': 'Pricing',
            'hero.subtitle': 'Leave the house cleaning chores to us',
            'hero.title': 'Let us do the dirty work, so you don\'t have to.',
            'services.subtitle': 'Services',
            'services.title': 'How We Work',
            'service.office.title': 'Office Cleaning',
            'service.office.desc': 'Comprehensive office cleaning to keep your workplace fresh, sanitized and professional for employees and visitors.',
            'service.pool.title': 'Pool Cleaning',
            'service.pool.desc': 'Specialized pool cleaning and chemical balancing to ensure clear, safe water and well-maintained pool areas.',
            'service.carpet.title': 'Carpet Cleaning',
            'service.carpet.desc': 'Deep carpet and rug cleaning using professional equipment to remove dirt, stains, and allergens for a healthier home.',
            'service.kitchen.title': 'Kitchen Cleaning',
            'service.kitchen.desc': 'Thorough kitchen cleaning and degreasing to ensure food-preparation areas are spotless and hygienic.',
            'service.garden.title': 'Garden Cleaning',
            'service.garden.desc': 'Garden and outdoor area maintenance to keep lawns, paths and patios tidy and inviting year-round.',
            'service.window.title': 'Window Cleaning',
            'service.window.desc': 'Professional window and glass cleaning for streak-free, crystal-clear views — inside and out.',
            'readmore': 'Read more',
            'project.subtitle': 'Our Project',
            'project.title': 'We have done many latest cleaning project',
            'project.house': 'House Cleaning',
            'project.window': 'Window Cleaning',
            'project.pool': 'Pool Cleaning',
            'project.office': 'Office Cleaning',
            'project.carpet': 'Carpet Cleaning',
            'project.garden': 'Garden Cleaning',
            'counter.subtitle': 'Happy Customer',
            'counter.title': 'Together we will explore new things',
            'counter.testimonies': 'Testimonies',
            'pricing.subtitle': 'Price & Plans',
            'pricing.title': 'Choose Your Perfect Plans',
            'pricing.maintenance': 'Maintenance Cleaning',
            'pricing.general': 'General Cleaning',
            'pricing.fixed': 'Fixed price – no hidden costs',
            'pricing.carpet.title': 'Carpets & Rugs Cleaning',
            'pricing.carpet.price': 'Price: 6 – 10 RON/m²',
            'pricing.carpet.minimum': '(minimum order 250 RON)',
            'pricing.room.title': 'Room-by-Room Services',
            'pricing.room.included': 'Included in general cleaning packages',
            'pricing.upholstery.title': 'Upholstery & Textiles Cleaning',
            'pricing.upholstery.desc': 'Professional cleaning without damaging materials',
            'contact.title': 'Contact Us',
            'contact.subtitle': 'Have questions or ready to book?',
            'contact.message': 'Send us a message and we\'ll get back to you as soon as possible!',
            'pricing.light.title': 'Light Maintenance',
            'pricing.light.dusting': 'Dusting visible surfaces',
            'pricing.light.bathroom': 'Bathroom maintenance',
            'pricing.light.kitchen': 'Kitchen surfaces',
            'pricing.light.vacuum': 'Vacuuming floors',
            'pricing.light.mopping': 'Mopping floors',
            'pricing.light.trash': 'Emptying trash bins',
            'pricing.light.min': 'Min. order: 250 RON',
            'pricing.standard.title': 'Standard Maintenance',
            'pricing.standard.all': 'All Light services',
            'pricing.standard.enhanced': 'Enhanced cleaning',
            'pricing.standard.appliances': 'Appliance exteriors',
            'pricing.standard.oven': 'Oven exterior',
            'pricing.standard.fridge': 'Refrigerator exterior',
            'pricing.standard.nodeep': 'No deep cleaning',
            'pricing.premium.title': 'Premium Maintenance',
            'pricing.premium.all': 'All Standard services',
            'pricing.premium.detailed': 'Detailed attention',
            'pricing.premium.extended': 'Extended surfaces',
            'pricing.premium.care': 'Premium care',
            'pricing.premium.nocabinets': 'No inside cabinets',
            'pricing.premium.noinside': 'No oven/fridge inside',
            'pricing.studio.title': 'Studio Apartment',
            'pricing.studio.complete': 'Complete cleaning',
            'pricing.studio.bathroom': 'Bathroom deep clean',
            'pricing.studio.kitchen': 'Kitchen deep clean',
            'pricing.studio.surfaces': 'All surfaces',
            'pricing.studio.vacuum': 'Vacuuming & mopping',
            'pricing.studio.fixed': 'Fixed price',
            'pricing.2room.title': '2-Room Apartment',
            'pricing.2room.living': 'Living room & bedroom',
            'pricing.3room.title': '3-Room Apartment',
            'pricing.3room.rooms': 'All rooms',
            'pricing.3room.extra': '2nd bathroom: +200 RON',
            'pricing.4room.title': '4-Room Apartment',
            'pricing.4room.rooms': 'All 4 rooms',
            'pricing.house.title': 'House / Villa',
            'pricing.house.bathrooms': 'All bathrooms',
            'pricing.house.custom': 'Custom quote available',
            'pricing.sofa.title': 'Sofa',
            'pricing.sofa.professional': 'Professional cleaning',
            'pricing.sofa.safe': 'Material-safe methods',
            'pricing.sofa.stain': 'Deep stain removal',
            'pricing.sofa.odor': 'Odor elimination',
            'pricing.sofa.other': 'Other models from 200 RON',
            'pricing.armchair.title': 'Armchair',
            'pricing.armchair.protection': 'Fabric protection',
            'pricing.mattress.title': 'Mattress',
            'pricing.mattress.deep': 'Deep cleaning',
            'pricing.mattress.mite': 'Dust mite removal',
            'pricing.mattress.allergen': 'Allergen elimination',
            'pricing.mattress.stain': 'Stain treatment',
            'pricing.mattress.sanitize': 'Sanitization',
            'pricing.chair.title': 'Upholstered Chair',
            'pricing.chair.quick': 'Quick drying',
            'pricing.chair.affordable': 'Affordable pricing',
            'pricing.carpet.small': 'Small Area',
            'pricing.carpet.deep': 'Deep carpet cleaning',
            'pricing.carpet.stain': 'Stain removal',
            'pricing.carpet.odor': 'Odor elimination',
            'pricing.carpet.fast': 'Fast drying',
            'pricing.carpet.eco': 'Eco-friendly products',
            'pricing.carpet.medium': 'Medium Area',
            'pricing.carpet.large': 'Large Area',
            'pricing.room.subtitle': 'Room-by-Room Services',
            'pricing.bathroom.title': '🛁 Bathroom',
            'pricing.bathroom.toilet': 'Toilet disinfection',
            'pricing.bathroom.tub': 'Bathtub/shower cleaning',
            'pricing.bathroom.limescale': 'Limescale removal',
            'pricing.bathroom.mirror': 'Mirror & glass cleaning',
            'pricing.bathroom.tiles': 'Tiles cleaning',
            'pricing.bathroom.floor': 'Floor disinfection',
            'pricing.bathroom.nocabinets': 'No inside cabinets',
            'pricing.kitchen.title': '🍽️ Kitchen',
            'pricing.kitchen.countertop': 'Countertop cleaning',
            'pricing.kitchen.tiles': 'Tiles/backsplash',
            'pricing.kitchen.cabinets': 'Cabinet fronts (exterior)',
            'pricing.kitchen.sink': 'Sink & tap anti-limescale',
            'pricing.kitchen.appliances': 'Appliances exterior',
            'pricing.kitchen.fridge': 'Inside fridge (extra)',
            'pricing.kitchen.oven': 'Inside oven (extra)',
            'pricing.living.title': '🛋️ Living Room',
            'pricing.living.dusting': 'Dusting all surfaces',
            'pricing.living.furniture': 'Furniture cleaning',
            'pricing.living.sofa': 'Sofa vacuuming',
            'pricing.living.doors': 'Doors & door frames',
            'pricing.living.baseboard': 'Baseboard wiping',
            'pricing.living.vacuum': 'Vacuuming floors',
            'pricing.living.mop': 'Mopping floors',
            'pricing.bedroom.title': '🛏️ Bedroom',
            'pricing.bedroom.dusting': 'Furniture dusting',
            'pricing.bedroom.nightstands': 'Nightstands & dressers',
            'pricing.bedroom.mirror': 'Mirror cleaning',
            'pricing.bedroom.vacuum': 'Vacuuming floors/carpet',
            'pricing.bedroom.mop': 'Mopping floors',
            'pricing.bedroom.doors': 'Doors & handles',
            'pricing.bedroom.nolinen': 'No bed linen change',
            'pricing.hallway.title': '🚪 Hallway',
            'pricing.hallway.dusting': 'Surface dusting',
            'pricing.hallway.doors': 'Doors & handles',
            'pricing.hallway.switches': 'Switches cleaning',
            'pricing.hallway.mirror': 'Mirror cleaning',
            'pricing.hallway.vacuum': 'Vacuuming floors',
            'pricing.hallway.mop': 'Mopping floors',
            'pricing.hallway.baseboard': 'Baseboard wiping',
            'button.getstarted': 'Get Started',
            'button.learnmore': 'Learn More',
            'contact.info': 'Contact Information',
            'contact.address': 'Address:',
            'contact.address.value': '203 Fake St. Mountain View, San Francisco, California, USA',
            'contact.phone': 'Phone:',
            'contact.email': 'Email:',
            'contact.whatsapp': 'WhatsApp:',
            'contact.getin': 'Get In Touch',
            'footer.description': 'CleanLine is a professional cleaning company specializing in Airbnb turnovers and general cleaning for houses and offices. We ensure spotless, well-prepared spaces with attention to detail, reliability, and high hygiene standards. Our goal is to help property owners and businesses maintain clean, welcoming environments effortlessly.',
            'footer.quicklinks': 'Quick Links',
            'footer.home': 'Home',
            'footer.about': 'About',
            'footer.services': 'Services',
            'footer.works': 'Works',
            'footer.blog': 'Blog',
            'footer.contact': 'Contact',
            'footer.questions': 'Have a Questions?',
            'testimony.title': 'Happy Customer'
        },
        ro: {
            'nav.home': 'Acasă',
            'nav.services': 'Servicii',
            'nav.portfolio': 'Portofoliu',
            'nav.pricing': 'Prețuri',
            'hero.subtitle': 'Lasă treburile de curățenie ale casei pe seama noastră',
            'hero.title': 'Lasă-ne pe noi să facem treaba murdară, ca tu să nu trebuie.',
            'services.subtitle': 'Servicii',
            'services.title': 'Cum Lucrăm',
            'service.office.title': 'Curățenie Birou',
            'service.office.desc': 'Curățenie completă de birou pentru a menține locul de muncă proaspăt, igienizat și profesional pentru angajați și vizitatori.',
            'service.pool.title': 'Curățenie Piscină',
            'service.pool.desc': 'Curățenie specializată de piscină și echilibrare chimică pentru a asigura apă clară, sigură și zone de piscină bine întreținute.',
            'service.carpet.title': 'Curățenie Covoare',
            'service.carpet.desc': 'Curățenie profundă a covoarelor și preșurilor folosind echipamente profesionale pentru a elimina murdăria, petele și alergenii pentru o casă mai sănătoasă.',
            'service.kitchen.title': 'Curățenie Bucătărie',
            'service.kitchen.desc': 'Curățenie amănunțită a bucătăriei și degresare pentru a asigura că zonele de preparare a alimentelor sunt impecabile și igienice.',
            'service.garden.title': 'Curățenie Grădină',
            'service.garden.desc': 'Întreținere grădină și zone exterioare pentru a menține gazonul, aleile și terasele curate și primitoare pe tot parcursul anului.',
            'service.window.title': 'Curățenie Ferestre',
            'service.window.desc': 'Curățenie profesională a ferestrelor și geamurilor pentru vederi cristaline, fără urme — interior și exterior.',
            'readmore': 'Citește mai mult',
            'counter.testimonies': 'Mărturii',
            'project.subtitle': 'Proiectul Nostru',
            'project.title': 'Am realizat multe proiecte de curățenie recente',
            'project.house': 'Curățenie Casă',
            'project.window': 'Curățenie Ferestre',
            'project.pool': 'Curățenie Piscină',
            'project.office': 'Curățenie Birou',
            'project.carpet': 'Curățenie Covoare',
            'project.garden': 'Curățenie Grădină',
            'counter.subtitle': 'Clienți Mulțumiți',
            'counter.title': 'Împreună vom explora lucruri noi',
            'pricing.subtitle': 'Prețuri & Planuri',
            'pricing.title': 'Alege Planurile Tale Perfecte',
            'pricing.maintenance': 'Curățenie de Întreținere',
            'pricing.general': 'Curățenie Generală',
            'pricing.fixed': 'Preț fix – fără costuri ascunse',
            'pricing.carpet.title': 'Curățenie Covoare & Preșuri',
            'pricing.carpet.price': 'Preț: 6 – 10 RON/m²',
            'pricing.carpet.minimum': '(comandă minimă 250 RON)',
            'pricing.room.title': 'Servicii Cameră cu Cameră',
            'pricing.room.included': 'Incluse în pachetele de curățenie generală',
            'pricing.upholstery.title': 'Curățenie Tapițerie & Textile',
            'pricing.upholstery.desc': 'Curățenie profesională fără deteriorarea materialelor',
            'contact.title': 'Contactează-ne',
            'contact.subtitle': 'Ai întrebări sau ești gata să rezervi?',
            'contact.message': 'Trimite-ne un mesaj și te vom contacta cât mai curând posibil!',
            'pricing.light.title': 'Întreținere Ușoară',
            'pricing.light.dusting': 'Ștergere praf suprafețe vizibile',
            'pricing.light.bathroom': 'Întreținere baie',
            'pricing.light.kitchen': 'Suprafețe bucătărie',
            'pricing.light.vacuum': 'Aspirare pardoseli',
            'pricing.light.mopping': 'Spălare pardoseli',
            'pricing.light.trash': 'Golire coșuri de gunoi',
            'pricing.light.min': 'Comandă minimă: 250 RON',
            'pricing.standard.title': 'Întreținere Standard',
            'pricing.standard.all': 'Toate serviciile Ușoare',
            'pricing.standard.enhanced': 'Curățenie îmbunătățită',
            'pricing.standard.appliances': 'Exterioare aparate',
            'pricing.standard.oven': 'Exterior cuptor',
            'pricing.standard.fridge': 'Exterior frigider',
            'pricing.standard.nodeep': 'Fără curățenie profundă',
            'pricing.premium.title': 'Întreținere Premium',
            'pricing.premium.all': 'Toate serviciile Standard',
            'pricing.premium.detailed': 'Atenție detaliată',
            'pricing.premium.extended': 'Suprafețe extinse',
            'pricing.premium.care': 'Îngrijire premium',
            'pricing.premium.nocabinets': 'Fără interior dulapuri',
            'pricing.premium.noinside': 'Fără interior cuptor/frigider',
            'pricing.studio.title': 'Apartament Garsonieră',
            'pricing.studio.complete': 'Curățenie completă',
            'pricing.studio.bathroom': 'Curățenie profundă baie',
            'pricing.studio.kitchen': 'Curățenie profundă bucătărie',
            'pricing.studio.surfaces': 'Toate suprafețele',
            'pricing.studio.vacuum': 'Aspirare & spălare',
            'pricing.studio.fixed': 'Preț fix',
            'pricing.2room.title': 'Apartament 2 Camere',
            'pricing.2room.living': 'Salon & dormitor',
            'pricing.3room.title': 'Apartament 3 Camere',
            'pricing.3room.rooms': 'Toate camerele',
            'pricing.3room.extra': 'A 2-a baie: +200 RON',
            'pricing.4room.title': 'Apartament 4 Camere',
            'pricing.4room.rooms': 'Toate cele 4 camere',
            'pricing.house.title': 'Casă / Vilă',
            'pricing.house.bathrooms': 'Toate băile',
            'pricing.house.custom': 'Ofertă personalizată disponibilă',
            'pricing.sofa.title': 'Canapea',
            'pricing.sofa.professional': 'Curățenie profesională',
            'pricing.sofa.safe': 'Metode sigure pentru materiale',
            'pricing.sofa.stain': 'Îndepărtare profundă pete',
            'pricing.sofa.odor': 'Eliminare mirosuri',
            'pricing.sofa.other': 'Alte modele de la 200 RON',
            'pricing.armchair.title': 'Fotoliu',
            'pricing.armchair.protection': 'Protecție țesătură',
            'pricing.mattress.title': 'Saltea',
            'pricing.mattress.deep': 'Curățenie profundă',
            'pricing.mattress.mite': 'Îndepărtare acarieni',
            'pricing.mattress.allergen': 'Eliminare alergeni',
            'pricing.mattress.stain': 'Tratament pete',
            'pricing.mattress.sanitize': 'Igienizare',
            'pricing.chair.title': 'Scaun Tapițat',
            'pricing.chair.quick': 'Uscare rapidă',
            'pricing.chair.affordable': 'Preț accesibil',
            'pricing.carpet.small': 'Suprafață Mică',
            'pricing.carpet.deep': 'Curățenie profundă covoare',
            'pricing.carpet.stain': 'Îndepărtare pete',
            'pricing.carpet.odor': 'Eliminare mirosuri',
            'pricing.carpet.fast': 'Uscare rapidă',
            'pricing.carpet.eco': 'Produse ecologice',
            'pricing.carpet.medium': 'Suprafață Medie',
            'pricing.carpet.large': 'Suprafață Mare',
            'pricing.room.subtitle': 'Servicii Cameră cu Cameră',
            'pricing.bathroom.title': '🛁 Baie',
            'pricing.bathroom.toilet': 'Dezinfectare toaletă',
            'pricing.bathroom.tub': 'Curățare cadă/duș',
            'pricing.bathroom.limescale': 'Îndepărtare calcar',
            'pricing.bathroom.mirror': 'Curățare oglindă & sticlă',
            'pricing.bathroom.tiles': 'Curățare faianță',
            'pricing.bathroom.floor': 'Dezinfectare pardoseală',
            'pricing.bathroom.nocabinets': 'Fără interior dulapuri',
            'pricing.kitchen.title': '🍽️ Bucătărie',
            'pricing.kitchen.countertop': 'Curățare blat',
            'pricing.kitchen.tiles': 'Faianță/lambriuri',
            'pricing.kitchen.cabinets': 'Fețe dulapuri (exterior)',
            'pricing.kitchen.sink': 'Chiuvetă & robinet anti-calcar',
            'pricing.kitchen.appliances': 'Exterior aparate',
            'pricing.kitchen.fridge': 'Interior frigider (suplimentar)',
            'pricing.kitchen.oven': 'Interior cuptor (suplimentar)',
            'pricing.living.title': '🛋️ Salon',
            'pricing.living.dusting': 'Ștergere praf toate suprafețele',
            'pricing.living.furniture': 'Curățare mobilier',
            'pricing.living.sofa': 'Aspirare canapea',
            'pricing.living.doors': 'Uși & tocuri',
            'pricing.living.baseboard': 'Ștergere plinte',
            'pricing.living.vacuum': 'Aspirare pardoseli',
            'pricing.living.mop': 'Spălare pardoseli',
            'pricing.bedroom.title': '🛏️ Dormitor',
            'pricing.bedroom.dusting': 'Ștergere praf mobilier',
            'pricing.bedroom.nightstands': 'Noptiere & comode',
            'pricing.bedroom.mirror': 'Curățare oglindă',
            'pricing.bedroom.vacuum': 'Aspirare pardoseli/covor',
            'pricing.bedroom.mop': 'Spălare pardoseli',
            'pricing.bedroom.doors': 'Uși & mânere',
            'pricing.bedroom.nolinen': 'Fără schimbat lenjerie pat',
            'pricing.hallway.title': '🚪 Hol',
            'pricing.hallway.dusting': 'Ștergere praf suprafețe',
            'pricing.hallway.doors': 'Uși & mânere',
            'pricing.hallway.switches': 'Curățare întrerupătoare',
            'pricing.hallway.mirror': 'Curățare oglindă',
            'pricing.hallway.vacuum': 'Aspirare pardoseli',
            'pricing.hallway.mop': 'Spălare pardoseli',
            'pricing.hallway.baseboard': 'Ștergere plinte',
            'button.getstarted': 'Începe Acum',
            'button.learnmore': 'Află Mai Mult',
            'contact.info': 'Informații de Contact',
            'contact.address': 'Adresă:',
            'contact.address.value': '203 Fake St. Mountain View, San Francisco, California, USA',
            'contact.phone': 'Telefon:',
            'contact.email': 'Email:',
            'contact.whatsapp': 'WhatsApp:',
            'contact.getin': 'Contactează-ne',
            'footer.description': 'CleanLine este o companie profesională de curățenie specializată în pregătirea proprietăților Airbnb și curățenie generală pentru case și birouri. Asigurăm spații impecabile, bine pregătite cu atenție la detalii, fiabilitate și standarde înalte de igienă. Scopul nostru este să ajutăm proprietarii și afacerile să mențină medii curate și primitoare fără efort.',
            'footer.quicklinks': 'Link-uri Rapide',
            'footer.home': 'Acasă',
            'footer.about': 'Despre',
            'footer.services': 'Servicii',
            'footer.works': 'Lucrări',
            'footer.blog': 'Blog',
            'footer.contact': 'Contact',
            'footer.questions': 'Ai Întrebări?',
            'testimony.title': 'Clienți Mulțumiți'
        }
    };

    // Current language
    let currentLang = localStorage.getItem('language') || 'en';

    // Initialize translation on page load
    function init() {
        // Set initial language
        updateLanguage(currentLang, false);

        // Add click event to language toggle button
        const languageToggle = document.getElementById('languageToggle');
        if (languageToggle) {
            languageToggle.addEventListener('click', function(e) {
                e.preventDefault();
                toggleLanguage();
            });
        }
    }

    // Toggle between languages
    function toggleLanguage() {
        currentLang = currentLang === 'en' ? 'ro' : 'en';
        updateLanguage(currentLang, true);
    }

    // Update all translatable elements
    function updateLanguage(lang, saveToStorage) {
        // Save preference to localStorage
        if (saveToStorage) {
            localStorage.setItem('language', lang);
        }

        // Update language indicator
        const currentLangElement = document.getElementById('currentLang');
        if (currentLangElement) {
            currentLangElement.textContent = lang.toUpperCase();
        }

        // Update HTML lang attribute
        document.documentElement.lang = lang;

        // Translate all elements with data-translate attribute
        const elements = document.querySelectorAll('[data-translate]');
        elements.forEach(function(element) {
            const key = element.getAttribute('data-translate');
            if (translations[lang] && translations[lang][key]) {
                element.textContent = translations[lang][key];
            }
        });

        // Add smooth transition effect
        elements.forEach(function(element) {
            element.style.transition = 'opacity 0.3s ease';
            element.style.opacity = '0';
            setTimeout(function() {
                element.style.opacity = '1';
            }, 50);
        });
    }

    // Wait for DOM to be ready
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

})();
